### ISSUE TITLE
Swap out SEMA logo in footer

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#10]
![sema_association- 1color](https://cloud.githubusercontent.com/assets/187030/5982400/30f368e8-a888-11e4-9f57-5f9747835ab8.png)

**Comment by DavidVaini** [comment]
whoever does this, when this is done, make sure to play with resizing the browser window to see what it looks like in mobile, I think the footer widths are very close to being thrown off with a different width image.
