### ISSUE TITLE
Part Page Title Tag

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#100]
The part number is rendering as undefined on part details page.

https://github.com/aries-auto/ariesautomotive/blob/master/src%2Fapp%2Fcontrollers%2Fpart%2Fpart.js#L50

**Comment by baseigneurie** [comment]
Replaced with the right field.

https://github.com/aries-auto/ariesautomotive/commit/eaba4576eaffbfaa2d35e2cff765c61d520e7801
https://github.com/aries-auto/ariesautomotive/commit/5d35a36cdc475a90ea3c6a320beac1848bf6f851
