### ISSUE TITLE
No content on web

### ISSUE THREAD

**Issue by etimme** [aries-auto/ariesautomotive#101]
Part B35-2010 is status 800 in the admin and has all necessary content and images but the web page is blank. 
![image](https://cloud.githubusercontent.com/assets/16309519/12762893/231b994c-c9b7-11e5-9161-0a56295bc48b.png)

**Comment by ninnemana** [comment]
I think this is left over data from http://admin.curtmfg.com/product/1231121548 and http://admin.curtmfg.com/product/1231121550.

**Comment by ninnemana** [comment]
All better
