### ISSUE TITLE
ARIES Application Guide Page Corrections

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#108]
On the app guide page on the ARIES site (http://www.ariesautomotive.com/appguides), there are a few category names that need correction.
- All spellings of "In" should be "IN"
- All spellings of "And" should be "and"
- "Wheel To Wheel" should be "Wheel-to-Wheel"
- "Aerotread" should be "AeroTread"
- "Advantedge" should be "AdvantEDGE" in all instances
- "Ridgestep" should be "RidgeStep"
- "Floor Liners" should be "StyleGuard Floor Liners"

Also, the PDF and Excel download links for AeroTread, AdvantEDGE side bars and RidgeStep direct to the ARIES homepage instead of downloading the appropriate documents.

**Comment by ninnemana** [comment]
Gotta talk to your friends in data about the app guide links.
