### ISSUE TITLE
ARIES Main Category Order

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#109]
The categories are out of order again on the ARIES site. Please change them to be displayed in the following order:

Front Ends
Sides
Accessories
Jeep
Interior

**Comment by ninnemana** [comment]
Weird that they all got set back to zero, is there something modifying the parent sort order when subcategories change?

``` sql
select catTitle, sort, catID from Categories
where brandID = 3 && parentID = 0
order by sort;
```

```
Sides	0	311
By Vehicle	0	317
Jeep	0	318
Interior	0	319
Accessories	0	322
Front Ends	0	323
```

**Comment by ninnemana** [comment]
There sure is: https://github.com/curt-labs/GoAdmin/blob/master/models/category/category.go#L357

**Comment by ninnemana** [comment]
This issue was moved to curt-labs/GoAdmin#252
