### ISSUE TITLE
Related Parts - OldPartNumber

### ISSUE THREAD

**Issue by 1brandeja5** [aries-auto/ariesautomotive#112]
Trying to add related parts to ARIES item
![image](https://cloud.githubusercontent.com/assets/15163363/13497310/466cd850-e11a-11e5-87e2-064725f24859.png)

2 questions:
1) Can we update the breadcrumbs on the attached page to reflect the OldPartNumber
2) Can we add related parts by OldPartNumber - it looks like the field prevents characters from being typed

Example: I am trying to add the 15600TW (tow hook) as a related item to the 2071030 (modular bumper).

**Comment by ninnemana** [comment]
This issue was moved to curt-labs/GoAdmin#254
