### ISSUE TITLE
Search Index Duplication

### ISSUE THREAD

**Issue by 1brandeja5** [aries-auto/ariesautomotive#113]
New item numbers are duplicated in search results if you search by item number:
P35-2010
B35-2010-3

*Update: doesn't appear to be limited to these item numbers.  I searched a 1042, 15600WRB, 15600TW - all showed duplicate results.

**Comment by ninnemana** [comment]
I think this is specific to ElasticSearch, I don't think they are being stored multiple times in MongoDB.

**Comment by stinkyfingers** [comment]
2fa96cf

**Comment by ninnemana** [comment]
Looks like it's still an issue? http://9.aries-auto.appspot.com/search/15600-0

**Comment by stinkyfingers** [comment]
Yeah, everything needs to be re-elasticked.

**Comment by stinkyfingers** [comment]
Oh, and Jenkins was down.

**Comment by stinkyfingers** [comment]
One bird with three goddam stones.

**Comment by stinkyfingers** [comment]
Reindexed.
