### ISSUE TITLE
No part details

### ISSUE THREAD

**Issue by stinkyfingers** [aries-auto/ariesautomotive#12]
Part is in DB and has shortDesc, yet page is blank.
http://aries-auto.appspot.com/part/B35-4004

**Comment by ninnemana** [comment]
I am doing a data transfer right now, so that could be causing probems..

**Comment by ninnemana** [comment]
`curl http://ariesautoapi.curtmfg.com/part/old/B35-4004?key=883d4046-8b96-11e4-9475-42010af00d4e`

`{
    message: "Trouble getting part by old part number",
    messageDetails: "sql: Scan error on column index 5: converting string "<nil>" to a int: strconv.ParseInt: parsing "<nil>": invalid syntax",
    request_body: "",
    query_string: {
       key: ["883d4046-8b96-11e4-9475-42010af00d4e"]
    }
}`

**Comment by ninnemana** [comment]
I'm going to close this in favor of https://github.com/curt-labs/GoAPI/issues/38
