### ISSUE TITLE
Moab Carousel and Landing Page

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#121]
Please use the photo from Kyle's email and the information below to create the carousel. You can replace the "Decked Out Jeep to be Donated to Navy SEAL Foundation" spot.

Headline: Team ARIES at Moab Jeep Safari 2016

Read more link: http://www.ariesautomotive.com/lp/37

Thank you!

**Comment by DavidVaini** [comment]
updated with this commit:
https://github.com/aries-auto/ariesautomotive/commit/d1794e23bae0172236d2e616b8627b11ae5fc6cb
