### ISSUE TITLE
2016 Honda HR-V StyleGuard Look Up

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#124]
Part HD05511509 isn't populating in the look up.
It is status 800 and is in the App data in Godzilla
![hr-v liner](https://cloud.githubusercontent.com/assets/11978902/14284533/9b6eaac4-fb0d-11e5-9761-dc4b84d345d5.png)

**Comment by stinkyfingers** [comment]
Status was not correct in MongoDB. Likely related to indexing issue #266 in GoAdmin.
