### ISSUE TITLE
FR09321502 Not Searchable

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#125]
FR09321502 is not populating results when searched on ARIES Site.
It does populate via the look up. It is status 800 in admin.

![image](https://cloud.githubusercontent.com/assets/11978902/14714586/2cbc552c-07ab-11e6-937b-8d2a49af61a9.png)

**Comment by ninnemana** [comment]
http://goapi.curtmfg.com/part/FR09321502?key=92ff4404-2ca6-11e4-8756-42a10a10fd89
http://iapi.curtmfg.com/index/part/1231121594?key=92ff4404-2ca6-11e4-8756-42a10a10fd89

Must not be updating, the images aren't populating either.

**Comment by stinkyfingers** [comment]
Duplicate parts FR09321502 and fr09321502.
