### ISSUE TITLE
CARiD.com Name Change

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#127]
CARiD.com wants there name to show up properly on the where to buy page. I don't get it, we're not using their logo or anything.

<img src="https://cloud.githubusercontent.com/assets/187030/14853954/4dc90d30-0c53-11e6-9b99-0bd0b1056419.png" width="400" />

Everything is being uppercased with a CSS rule: https://github.com/aries-auto/ariesautomotive/blob/master/src%2Fapp%2Fsass%2Fwheretobuy.scss#L298. My worry is that we remove that rule and the rest of them are going to look terrible because no attention was given to how they were added. /cc @cowan14 

After we know that they aren't going to look like garbage and have some consistency, let's remove that CSS rule.

**Comment by cowan14** [comment]
Everything is good to go in the Admin. Make the switch on ARIES.

**Comment by altruistictravy** [comment]
Could you make sure they land on: http://www.carid.com/aries-automotive/ ?

**Comment by cowan14** [comment]
added link Travis
