### ISSUE TITLE
Highlighting the Vehicle Lookup

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#128]
Would it be possible to put a flashbulb effect on the vehicle lookup bar after someone clicks the "Find Products for Your Vehicle" button at the bottom of the category pages? Right now, when someone clicks that button, it takes them to the top of the page, and from a consumer view, it almost seems like the link isn't taking them to the right spot, like it should be directing to a new page, even though it's correctly bringing them to the lookup. If we put a flashbulb effect on it that would fade over a two-second period (or some brief amount of time), it would make the direction more clear.

**Comment by stinkyfingers** [comment]
@ninnemana What do you think?

**Comment by ninnemana** [comment]
The CURT site prompts the lookup into a shadowbox effect, I'd say that, if anything.

**Comment by ninnemana** [comment]
We now include products in the category response that work for a configured vehicle.
