### ISSUE TITLE
Image not showing on Part Results page

### ISSUE THREAD

**Issue by 1brandeja5** [aries-auto/ariesautomotive#129]
Any ideas on why the image would not show up on the part result page, but it does exist for the part details page?

Part Results:
![image](https://cloud.githubusercontent.com/assets/15163363/14987289/fba978ca-1114-11e6-812c-670f70c55b90.png)

Part Details:
![image](https://cloud.githubusercontent.com/assets/15163363/14987304/0ffbc580-1115-11e6-94c3-bbe0383b35dc.png)

**Comment by 1brandeja5** [comment]
in a potentially related note: it is also status 600 in the admin 💭 

![image](https://cloud.githubusercontent.com/assets/15163363/14987702/343eea20-1116-11e6-9516-8705c6474ab5.png)

**Comment by DavidVaini** [comment]
It shows up in the admin as a status 600 part.

I noticed when I searched for just the part number it didn't come up. Weird that it shows up on the vehicle parts page as it is a status 600 part. I'd imagine a status 600 part should not show up on the website at all, even with a vehicle search.

**Comment by 1brandeja5** [comment]
I imagine you to be correct 👍  Can we determine why it would be acting a fool?

**Comment by DavidVaini** [comment]
The Part was showing up twice in the Mongo Collection, once as status 800 and once as status 600. I removed both of the, re-indexed the part. Now there is only one in the Mongo Collection as status 600 and it does not show up when you do the same vehicle lookup now.

**Comment by 1brandeja5** [comment]
thank you sir... any idea how/why this could be allowed?

**Comment by DavidVaini** [comment]
Not sure, looking into it, Maybe when a part status gets changed it adds a new record in mongo rather than updating the old record?

**Comment by 1brandeja5** [comment]
well that sounds dangerous - let us (data team) know if there is anything from the process of entry we can do to prevent this from happening again

**Comment by ninnemana** [comment]
Usually this happens when a part was added with one part number, but then they change the part number and it creates duplicates. iAPI uses the part number as an insert/update decision, it should really use the primary key (`partID`) instead of part number (`oldPartNumber`).

**Comment by DavidVaini** [comment]
okay, I can change that over, it looks to be using this function:
https://github.com/curt-labs/iapi/blob/master/fanner%2Fproduct%2Fproduct.go#L252

When it could just find by the primary key.

**Comment by DavidVaini** [comment]
fixed future issues with this commit:
https://github.com/curt-labs/iapi/commit/2cf93bf6b4c033e669532b78ca67950a5e6d65dd

Working on finding and removing duplicates in mongo right now.

**Comment by ninnemana** [comment]
Fixed?

**Comment by 1brandeja5** [comment]
Yep looks good.
