### ISSUE TITLE
No images or content

### ISSUE THREAD

**Issue by etimme** [aries-auto/ariesautomotive#130]
When searching for part 2911002 I came across the below parts. The part pages are blank but there is content in the admin for these parts. 

![image](https://cloud.githubusercontent.com/assets/16309519/15127854/2ab9d46e-15fe-11e6-818d-a89f0db95409.png)
![image](https://cloud.githubusercontent.com/assets/16309519/15127876/5565189a-15fe-11e6-8e08-57c03cc11d2f.png)
![image](https://cloud.githubusercontent.com/assets/16309519/15127882/5d5ce136-15fe-11e6-9bae-4baed14a8803.png)

**Comment by stinkyfingers** [comment]
![screen shot 2016-05-10 at 8 55 53 am](https://cloud.githubusercontent.com/assets/4924621/15149032/983988d8-168d-11e6-8df5-8e589ca64052.png)
![screen shot 2016-05-10 at 8 57 51 am](https://cloud.githubusercontent.com/assets/4924621/15149031/982cad5c-168d-11e6-9251-ee724d0a5089.png)
![screen shot 2016-05-10 at 8 58 23 am](https://cloud.githubusercontent.com/assets/4924621/15149030/982c5c80-168d-11e6-9e85-6539101495b3.png)
![screen shot 2016-05-10 at 8 58 39 am](https://cloud.githubusercontent.com/assets/4924621/15149028/9829da6e-168d-11e6-9621-8689a6e0f25b.png)
![screen shot 2016-05-10 at 8 59 39 am](https://cloud.githubusercontent.com/assets/4924621/15149027/982931f4-168d-11e6-8f1d-30a801e222c5.png)
![screen shot 2016-05-10 at 8 59 51 am](https://cloud.githubusercontent.com/assets/4924621/15149029/982be58e-168d-11e6-9c07-6f5531518d89.png)

Am I missing something? I'm 0 for 3 on images and attributes.

**Comment by etimme** [comment]
I don't see images or attributes either, I can look in to that. 
Some of these though, such as TY04431509, have content in the Part Content page but their part page on the web is blank. This part is also using the wrong description. 
![image](https://cloud.githubusercontent.com/assets/16309519/15149640/f7ef74b6-168f-11e6-94a9-cc6e9dad19f1.png)
![image](https://cloud.githubusercontent.com/assets/16309519/15149658/0dddd6dc-1690-11e6-80b4-11a07272c836.png)
![image](https://cloud.githubusercontent.com/assets/16309519/15149678/1fee3c0e-1690-11e6-8998-c67ade84df40.png)

**Comment by ninnemana** [comment]
Clicked the save button and all is well with `TY04431509`: http://www.ariesautomotive.com/part/TY04431509

**Comment by ninnemana** [comment]
Was the content added for these parts via the content upload? If so, is the content upload triggering the fan-out process?

**Comment by etimme** [comment]
As far as I know the content wasn't added via the upload. The descriptions for some of these look like the descriptions from XA.

**Comment by ninnemana** [comment]
Ok, @stinkyfingers can you verify that changing a products `Content` in the admin (http://admin.curtmfg.com/product/11000/content) triggers the fan-out process?

**Comment by stinkyfingers** [comment]
https://github.com/curt-labs/GoAdmin/blob/master/models/part/content.go#L187 There must be a bug somewhere else.

**Comment by stinkyfingers** [comment]
@etimme Any idea when some of the content in question would have been added/uploaded? Recent changes?

**Comment by etimme** [comment]
The only recent changes these parts may have had would be in the status. To my knowledge we have not updated or added any content to these parts recently.

**Comment by stinkyfingers** [comment]
Boom. Sounds great. I feel like I'm chasing a bug that USED to exist.
