### ISSUE TITLE
ARIES Website Pages

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#134]
I would like the capability to create content pages for ARIES in the admin. Right now, the capability exists for CURT, but after talking with David and John, it sounds like it doesn't exist for ARIES yet.

**Comment by ninnemana** [comment]
Where should these content pages be linked from? Like where on the website should the links to said content pages reside? On the CURT site you have the following places:

![image](https://cloud.githubusercontent.com/assets/187030/15614599/5fac0ce6-23ff-11e6-9736-495d7c58d58e.png)
![image](https://cloud.githubusercontent.com/assets/187030/15614683/c0356922-23ff-11e6-872a-6fc21e527abf.png)

If you don't want to create menus for the content pages on the site, why not use the landing pages features that already exists?

**Comment by aaronrodgersmoustache** [comment]
My intention for this is to create an equivalent Understanding Towing section called the Auto Accessories Guide. It will be made up of five to ten pages for now. I would only need a single link somewhere on the ARIES homepage.

I could definitely use the landing pages feature. David and John thought that that might not work, though.

**Comment by ninnemana** [comment]
@DavidVaini / @stinkyfingers what was the hesitation?

**Comment by stinkyfingers** [comment]
This can totally work. The hesitation was...are we okay to green-light this?

**Comment by ninnemana** [comment]
Everything should be in place to support this for creating the landing pages, we just don't have a link to it from somewhere on the homepage. We couldn't add it to the top nav, it would probably have to go in the footer.
