### ISSUE TITLE
Vehicle lookup flicker

### ISSUE THREAD

**Issue by stinkyfingers** [aries-auto/ariesautomotive#137]
When looking up a vehicle, the vehicle lookup will show the vehicle you previously looked up, if there was one, before rendering the new vehicle. Server->client rendering issue?

**Comment by 1brandeja5** [comment]
This also occurs each time you go to a product page - it can be a bit confusing.

**Comment by ninnemana** [comment]
I've deployed [refactor/vehicle-flicker](https://github.com/aries-auto/ariesautomotive/tree/refactor/vehicle-flicker) to https://flicker-dot-aries-auto.appspot.com for testing.
