### ISSUE TITLE
vehicle lookup: selected vehicle and navigating away

### ISSUE THREAD

**Issue by mickelsonm** [aries-auto/ariesautomotive#14]
I think we may need to look at the lookup from a user's perspective. For example, when the user selects a vehicle w/ configurations, then clicks on View Parts. They see their results, which is what we expect.

However, after seeing the results, if they navigate away to a different section of the website, there is no way to get back to their results (other than clicking the back button on the browser...). They continue to see what vehicle they have selected, but I don't think it applies to anything else on the website. Also, on the lookup by clicking Change it resets the entire lookup, so there's no way for them to use their selected vehicle to return that way either....

**Comment by ninnemana** [comment]
This was fixed here https://github.com/aries-auto/ariesautomotive/commit/b8f35d2d434a7defe1eda430adcc3ced3d4940d1, maybe cached?

**Comment by mickelsonm** [comment]
Yup, caching problems it seems.
