### ISSUE TITLE
Vehicle Lookup Restyling

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#142]
This is an effort to restyling the category/product display of the vehicle results page. There is a separate effort in the works that is integrating envisionARIES into the vehicle lookup (https://github.com/aries-auto/ariesautomotive/issues/95). This will need to be aware of the additions being made on that effort and incorporate that project into the go-live implementation.

**One adjustment to the attached screenshot**
There is a third, darker gray navbar, that will not be incorporated into the implementation. The lookup will instead function like the current version, where a selected vehicle replaces the `<select>` options.

![aries-lookup-page-mockup](https://cloud.githubusercontent.com/assets/187030/16066850/83b2c658-327c-11e6-8471-2df32152e31d.png)

**Comment by baseigneurie** [comment]
So I noticed the example provided groups categories (running boards, nerf bars, ovals, etc.) for the lookup results. The data structure isn't currently set up for that and I'm curious if this will be added at some point? Or is there going to be a new dataset made specifically going forward?

I noticed @DavidVaini ran into this issue with https://github.com/aries-auto/ariesautomotive/issues/143 and he set up a group collection for the appguide categories. I can setup something similar, I'm just not sure if what's built around it will be permanent.

**Comment by DavidVaini** [comment]
This looks to be the exact structure that we are using for App Guide Groups and App Guides. I see no reason why that structure couldnt be used for this.

The only thing I'd question is if they want a different organizational structure/categories than the app guides. I would vote for consistency and use the same structure/same groups.
What do you think @aaronrodgersmoustache  and @1brandeja5 ?

**Comment by aaronrodgersmoustache** [comment]
If you mean the app guide page itself, then yes, the vehicle lookup should follow the same structure as the app guide page. If you mean the app guides themselves, then no. The bull bars app guide, for example, has several product categories combined into one spreadsheet. For the app guide page, I still want to show each individual product category, but just have them all link to the one shared file.

**Comment by ninnemana** [comment]
This shouldn't be any more effort than restyling the data that's already available. You have product categories, which have images and titles. Those categories have products that are grouped by categories. There should be no need for modifying the API calls at all. Don't over complicate it.

**Comment by DavidVaini** [comment]
The images for the categories are jpgs, when a sub category is clicked, it changes to have a red background. 

The image background is white and so it doesnt work with the design mentioned above. @cowan14  could we update the category images to be png's with transparent backgrounds? They can be updated on the edit categories page in the admin
_Example:_ http://admin.curtmfg.com/categories/332

Thanks.

**Comment by DavidVaini** [comment]
I notice the content below "Vehicle look up results" seems to be content written for the app guides and doesnt apply here. Are we going to have different content written for this section? @aaronrodgersmoustache

**Comment by cowan14** [comment]
Updated all category images with PNG's.

**Comment by DavidVaini** [comment]
thanks @cowan14  👍

**Comment by aaronrodgersmoustache** [comment]
Where is this content appearing? Can you provide a link?

**Comment by ninnemana** [comment]
@aaronrodgersmoustache I think he's referring the the paragraph under `Vehicle Lookup Results` in the image above that states the following:

```
The application guides below will help you determine which ARIES parts will fit your vehicle.
Each app guide is category-specific and broken down by vehicle make, model, year and style.
```

**Comment by ninnemana** [comment]
@DavidVaini looks like the breadcrumbs are missing in the staging version.

**Comment by aaronrodgersmoustache** [comment]
@DavidVaini please use the following text:
Choose a category below to see the products that fit your vehicle.
Some products may require the style of the vehicle to be specified.

**Comment by 1brandeja5** [comment]
What is the link to see this version of the site? @DavidVaini

**Comment by ninnemana** [comment]
https://lookup-dot-aries-auto.appspot.com/vehicle/2015/CHEVROLET/SILVERADO 1500

**Comment by ninnemana** [comment]
This has been implemented for ARIES and Luverne and will be rolled into the live site in the navigation re-branding.
