### ISSUE TITLE
View All Products

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#144]
We will need to added a `View All Products` category tree to site. If we don't do it for the consumer effort, we should at least make a clickable navigation and drop the `View All` link in the footer. This may be a simple thing using [Get Categories](api.curtmfg.com/v3/category?key=9300f7bc-2ca6-11e4-8758-42010af0fd79) or it might be difficult.

**Comment by ninnemana** [comment]
After review, we've decided to make the following change:

Create a page (/category) that queries for the root of the category hierarchy and generates a display of the category tree with links to each individual product category.

There will be some marketing copy the we will want to insert into the top of the page, this should be able to queried from the CMS using the /api/content/slug endpoint that's being called for each route.

**Comment by DavidVaini** [comment]
Is there any format we want this to be displayed in? Do we want just the category titles in a tree type display, or do we want the category images shown as well? 

Does graphics have any insight on how they want this page to look?

In the mean time, I can just wing it if thats what we want to do.

**Comment by aaronrodgersmoustache** [comment]
Can you follow this page as a template?
http://www.ariesautomotive.com/page/132

**Comment by DavidVaini** [comment]
We sort of can. There can be more than 2 levels of category tiers when we go live with this. The example you show only has 2 levels of categories.

Example:
Exterior -> Sides -> 3 IN Round Side Bars

sometimes its only 2:
Interior -> Seat Defender

So it will be slightly different. (an additional Heading for the 1st level tier (Interior or Exterior)

The display will have to be something like how we are doing on the new lookup restyling here: https://github.com/aries-auto/ariesautomotive/issues/142

The problem with this approach is you no longer show "Interior/Exterior" as viable categories. Maybe this is okay?

**Comment by aaronrodgersmoustache** [comment]
Sounds good to me.

**Comment by DavidVaini** [comment]
This is what it looks like right now:
https://xhr-david-dot-aries-auto.appspot.com/category

The category images had white backgrounds, so I had to tweak the styling a little bit.

**Comment by DavidVaini** [comment]
I went ahead and updated the category image, its still cached so it will take about a day to update.

I am going to go ahead and close this issue since I merged in the code into refactor/xhr-sourcing

https://github.com/aries-auto/ariesautomotive/commit/39c9e299d49218b37079f6dd852729f6bdb83284
