### ISSUE TITLE
Category Sorting

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#147]
The category sorting tool in the admin does not seem to be working. I tried saving each of the categories in the edit page, which has worked in the past, but to no avail. I also tried tampering with the sort and saving again, but it didn't change.

**Comment by stinkyfingers** [comment]
Closed with admin 7161f26

**Comment by ninnemana** [comment]
I'm going to let you have the credit, but my fix was clearly the best fix of the morning. e04aaf7703b2f46f6a994cbdfa73d1aa907f79ff
