### ISSUE TITLE
AeroTread Boards Showing Up Twice in Look Up Results

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#148]
![image](https://cloud.githubusercontent.com/assets/11978902/16119910/3bc8419c-33a3-11e6-85f7-44917c0fa30f.png)

**Comment by stinkyfingers** [comment]
![screen shot 2016-06-16 at 9 33 34 am](https://cloud.githubusercontent.com/assets/4924621/16120572/87805474-33a5-11e6-85e5-b1da09227ee6.png)
I see duplicates in the admin. Logic error or input duplicates?

**Comment by 1brandeja5** [comment]
Hey @mcrandell did you get a chance to check the file you loaded to Godzilla to see if they were input multiple times or is it an issue with the import logic?

**Comment by mcrandell** [comment]
Duplicates removed from EDS. Have process in place to check if boards already are assigned to application before entering into EDS w/ kits.
