### ISSUE TITLE
Implement Share Icons

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#15]
The share icons on part details page need to have an action tied to them.

Copy the wording the CarID uses for their share actions.

**Comment by DavidVaini** [comment]
Implemented them into the Master branch here:
https://github.com/aries-auto/ariesautomotive/commit/3b7b1cbaa7c87f0c7073a40949be6b198ecf3bfa

I just need to put them in the godzilla branch as well and then ill close this issue.

**Comment by DavidVaini** [comment]
Also implemented on the godzilla branch:
https://github.com/aries-auto/ariesautomotive/commit/b29b8d0803ec6cd72d19b7cf0606ff95be421d4f
