### ISSUE TITLE
Content not showing up for 364009-2

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#152]
Content is in admin, but not showing up on part page......tried re-saving part too. 

![image](https://cloud.githubusercontent.com/assets/6673274/16162175/70c475ba-3497-11e6-9536-5e3374470f46.png)

**Comment by ninnemana** [comment]
Duplicate entries in Mongo, fixed it.

**Comment by baseigneurie** [comment]
Thank you. I was just about to check there, but you beat me to it.
