### ISSUE TITLE
2055542 not loading

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#153]
Part shows up in search. go to part details and it just sits on loading.

![image](https://cloud.githubusercontent.com/assets/11978902/16163190/88ac6998-349d-11e6-9821-7efc90ed2a0f.png)

**Comment by ninnemana** [comment]
¯\_(ツ)_/¯ re-saved and it's all set. new part?

**Comment by mcrandell** [comment]
launched this part earlier this week.

**Comment by ninnemana** [comment]
Must've died in the distribution process, made it into search and no further...
