### ISSUE TITLE
Dealer Portal - Item Display (inventory)

### ISSUE THREAD

**Issue by 1brandeja5** [aries-auto/ariesautomotive#156]
It looks like the item data is not coming in right when trying to buy a product.  

dealers.ariesautomotive.com
test@curtmfg.com account

![image](https://cloud.githubusercontent.com/assets/15163363/16211414/f3c20f60-3706-11e6-9c85-ee02e35fd5d0.png)

**Comment by stinkyfingers** [comment]
Closed w/ dealers dc6b46e250155dcfb8493ee96b35dda32b37c9ce
