### ISSUE TITLE
Mass image import tool not working in admin

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#157]
Mass image import tool not working in admin.

Image scrape/upload tool from FTP to website

![image](https://cloud.githubusercontent.com/assets/6673274/16230337/89fdb680-3786-11e6-84a9-81619cc6b9fe.png)

**Comment by DavidVaini** [comment]
problem with redis issue, temp fix here:
https://github.com/curt-labs/GoAdmin/commit/0925393e8a35c81a3f3d2a353cc460ec3dad484b
