### ISSUE TITLE
Dealer portal - failed to add to cart

### ISSUE THREAD

**Issue by 1brandeja5** [aries-auto/ariesautomotive#158]
I am attempting to add the 203044 to my cart - I can successfully complete this operation in ComNET, but am unable to do so in the dealer portal:
![image](https://cloud.githubusercontent.com/assets/15163363/16268110/9abbcc6a-3852-11e6-904d-491cced9a382.png)

**Comment by 1brandeja5** [comment]
![image](https://cloud.githubusercontent.com/assets/15163363/16268125/ad5268fc-3852-11e6-88e0-bab92ae681a9.png)

**Comment by stinkyfingers** [comment]
Closed w/ iapi 336064909bcce556a2a5bcf696971c49fc60a4bc.
