### ISSUE TITLE
Header Box Model

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#16]
Fix the box model in the header, it's causing problems with vertical centering.

https://www.dropbox.com/s/qc50unbmdigzmk4/Screenshot%202015-02-27%2010.58.43.png?dl=0

**Comment by DavidVaini** [comment]
This issue appears to be fixed.

**Comment by ninnemana** [comment]
Fixed here 9857665f227c7a3740e0f40ab370a2488656bb8b
