### ISSUE TITLE
ARIES Auto Accessories Guide

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#162]
I've created some landing pages for the ARIES site, and I'm having trouble publishing them. The dates are set correctly, so the page should be visible. However, when I click "View", it comes up with a page that says "Page not found". How do I make these landing pages live?

Also, I would like to add a link in the footer to the page below. I'm not sure that I'm able to do this in the admin. The link should be titled "AUTO ACCESSORIES GUIDE".

 http://www.ariesautomotive.com/lp/46

**Comment by DavidVaini** [comment]
I will meet with you shortly to discuss this.
