### ISSUE TITLE
Excessive API calls

### ISSUE THREAD

**Issue by stinkyfingers** [aries-auto/ariesautomotive#164]
Vehicle pages like http://localhost:3000/vehicle/2006/FORD/F-150 

Hit goapi:
/vehicle/mongo/allCollections -  5 times
/site/content/all - 2 times
/category/320/parts - 2 times
/vehicle/mongo/iconMediaVehicle - 2 times
/vehicle/mongo/categoryStyleParts - 2 times
/geography/countrystates - 2 times

Seems a little unnecessary, especially the allCollections call.

**Comment by ninnemana** [comment]
This is really creating a lot of overhead on page load. Can we eliminate the `allCollections` call entirely?

**Comment by ninnemana** [comment]
I've been working on this in [refactor/slim-xhr](https://github.com/aries-auto/ariesautomotive/tree/refactor/slim-xhr)

**Comment by ninnemana** [comment]
Fixed in https://github.com/aries-auto/ariesautomotive/tree/refactor/xhr-sourcing
