### ISSUE TITLE
Typekit Font Loading

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#167]
There seems to be lag in the rendering of the TypeKit font pack, which is causing a bit of annoyance for the user.

**Comment by stinkyfingers** [comment]
http://blog.typekit.com/2013/08/21/best-practices-for-embedding-typekit/
Hmmm...I like that Typekit's own blog about best practices has the same lag.

**Comment by ninnemana** [comment]
Seems better. We'll close it until we hear otherwise.

**Comment by ninnemana** [comment]
This is still a fairly obnoxious problem. Maybe we can fix by implementing [webfontloader](https://github.com/typekit/webfontloader) as described here: https://css-tricks.com/loading-web-fonts-with-the-web-font-loader. Some of it will have to be adapted to a reactjs approach.

**Comment by ninnemana** [comment]
Fixed with https://github.com/aries-auto/ariesautomotive/tree/refactor/xhr-sourcing
