### ISSUE TITLE
Browser test in safari

### ISSUE THREAD

**Issue by pmcginley** [aries-auto/ariesautomotive#17]
Lee thinks site looks "funky" in safari - 
check fonts - css - etc.

Menu options do not load - Vehicle lookup dropdowns do no function in Safari for Windows.

![image](https://cloud.githubusercontent.com/assets/259677/6442094/c9d1ddb4-c0b2-11e4-83a9-ef1cb04ca52f.png)

**Comment by ninnemana** [comment]
Hmm, osx safari is ok https://www.dropbox.com/s/h4b1azamzkeha93/Screenshot%202015-03-02%2008.26.31.png?dl=0

**Comment by ninnemana** [comment]
http://9to5mac.com/2013/09/19/farewell-windows-safari-as-apple-excludes-from-icloud-bookmark-sync/

Apple hasn't supported Safari on Windows for over a year, do we care?

**Comment by DavidVaini** [comment]
Something to note, Safari 5.1.7 released in May 9, 2012 is the last supported version, current marketshare looks to be less than .3%
