### ISSUE TITLE
ARIES About Us Page

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#171]
Is there a way that I can edit the ARIES About Us page (http://www.ariesautomotive.com/about), using the admin? I see there's a content page called "ARIES - About", but this doesn't have any content? If I add content to it, will it show up on the About page on the ARIES site?

**Comment by ninnemana** [comment]
Currently is doesn't, but we could easily make this possible. How about you fill out the content you want in the `ARIES - About` content page in the admin, and we'll disable the "default" content that is there now. Deal?

**Comment by ninnemana** [comment]
This has been implemented in the new design https://github.com/aries-auto/ariesautomotive/tree/refactor/xhr-sourcing and will be implemented when that's merged into master.
