### ISSUE TITLE
4" Oval Side Bar Wheel To Wheel App Guide

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#173]
4" Wheel-to-Wheel app guide not being pulled up when you click hte .xls or pdf link

![image](https://cloud.githubusercontent.com/assets/11978902/17114190/74d54072-5273-11e6-9779-f8f9a3553e1b.png)

![image](https://cloud.githubusercontent.com/assets/11978902/17146967/27bae892-5326-11e6-9259-11193135bcb4.png)

**Comment by mcrandell** [comment]
The 5.5 IN Advantedge side bar links pull up the incorrect app guide as well.
![image](https://cloud.githubusercontent.com/assets/11978902/17146893/d5ec74ea-5325-11e6-872f-30f17c525d2f.png)

**Comment by mcrandell** [comment]
![image](https://cloud.githubusercontent.com/assets/11978902/17146915/e980cc86-5325-11e6-8263-97328b6c0a4d.png)

**Comment by mcrandell** [comment]
Same problem with RidgeStep Running Boards going to the wrong app guides

![image](https://cloud.githubusercontent.com/assets/11978902/17147004/4dd4a996-5326-11e6-85dc-b50287048a1f.png)

**Comment by mcrandell** [comment]
![image](https://cloud.githubusercontent.com/assets/11978902/17147030/6ee9961e-5326-11e6-90eb-0ca01d127323.png)

**Comment by baseigneurie** [comment]
The appropriate appguides should now be downloading. https://github.com/aries-auto/ariesautomotive/commit/4281fa9e0782210cad5f286731500680ff06b967

**Comment by baseigneurie** [comment]
I think we have a new problem 
<img width="429" alt="screen shot 2016-07-29 at 3 46 36 pm" src="https://cloud.githubusercontent.com/assets/7674939/17262912/ca163310-55a3-11e6-812a-b89d66a381b1.png">

**Comment by ninnemana** [comment]
Wouldn't call it a new problem https://github.com/aries-auto/ariesautomotive/blob/master/src/components/AppGuides/AppGuide/data.js#L39-L48

**Comment by baseigneurie** [comment]
The proper app guides are downloading once again. Closing now.
