### ISSUE TITLE
2055104 Not populating in look up results

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#177]
ARIES Part# 2055104 isn't populating in look up results.
Part is status 800 and i've resaved the part multiple times.
Part applies to following applications:
2015-2016 Chevrolet Colorado Crew Cab
2015-2016 Chevrolet Colorado Extended Cab
2015-2016 GMC Canyon Crew Cab
2015-2016 GMC Canyon Extended Cab

![image](https://cloud.githubusercontent.com/assets/11978902/17740151/34a06bd4-645d-11e6-84f2-53d33fe5305b.png)

**Comment by ninnemana** [comment]
I believe the lookup results are on a 24 caching cycle, that may have been why it wasn't showing up. Looks to be populating now (http://www.ariesautomotive.com/vehicle/2015/CHEVROLET/COLORADO), it's showing multiple times, but I have a feeling that's related to #178
