### ISSUE TITLE
2055111 Duplicate Results in Look Up

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#178]
ARIES Part 2055111 is duplicating in the look up results.
Applications for part are:
2011-2016 RAM 2500 Mega Cab
2011-2016 RAM 3500 Mega Cab
Part is only appearing once in the Godzilla DB

![image](https://cloud.githubusercontent.com/assets/11978902/17740568/b91ff00e-645e-11e6-97ab-7d6feb51485b.png)

**Comment by ninnemana** [comment]
Looks like the distribution process is creating duplicate vehicle fitments: http://iapi.curtmfg.com/index/part/1231121527?key=92ff4404-2ca6-11e4-8756-42a10a10fd89

**Comment by ninnemana** [comment]
This issue was moved to curt-labs/iapi#49
