### ISSUE TITLE
Video Report Not Working

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#179]
![image](https://cloud.githubusercontent.com/assets/6673274/17754720/8576b50c-649b-11e6-92b5-e12ad4ef4987.png)

**Comment by DavidVaini** [comment]
It worked for me, I was able to generate a report, I emailed it to @cowan14. It didnt work yesterday for me, so I will take a look into this further.

**Comment by DavidVaini** [comment]
closed with these commits:
https://github.com/aries-auto/dealers/commit/a0c9502b87dcf83e7246f57a16bc140c82f2fb99
https://github.com/aries-auto/dealers/commit/b4acf933b4f93557dce5eb7aab5eb73e0143bf15
