### ISSUE TITLE
ARIES Image and INS Reports not working

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#180]
Can't generate ARIES Image or INS reports. Need them for customers.
![image](https://cloud.githubusercontent.com/assets/11978902/17783454/bc603672-653d-11e6-8d00-089e41768026.png)

![image](https://cloud.githubusercontent.com/assets/11978902/17783459/c3180760-653d-11e6-9a6e-21d7c47f3479.png)

**Comment by ninnemana** [comment]
This is going well, eh?

**Comment by DavidVaini** [comment]
It was a problem with all of the media reports, I just fixed it with these commits:
https://github.com/aries-auto/dealers/commit/a0c9502b87dcf83e7246f57a16bc140c82f2fb99
https://github.com/aries-auto/dealers/commit/b4acf933b4f93557dce5eb7aab5eb73e0143bf15
If it does not work for you, refresh the page, just in case the javascript is cached.
