### ISSUE TITLE
2055104 Not showing in lookup

### ISSUE THREAD

**Issue by etimme** [aries-auto/ariesautomotive#181]
Part 2055104 doesn't show up in the AdvantEdge 5.5" Side Bars category when looking up a 2015-2016 Chevrolet Colorado or GMC Canyon. It appears to be correct when looking in godzilla and shows up correctly in the RidgeStep category. 

![image](https://cloud.githubusercontent.com/assets/16309519/17819993/2f5c99ea-6610-11e6-988d-2ec11e83e9ed.png)

![image](https://cloud.githubusercontent.com/assets/16309519/17819997/398ad526-6610-11e6-9a17-548f211ba3be.png)

**Comment by ninnemana** [comment]
That's a real bummer @etimme. I thought I fixed it in #177


![](http://i.imgur.com/FG39BTa.gif)

**Comment by mcrandell** [comment]
@ninnemana any update on this?

**Comment by DavidVaini** [comment]
this was fixed with my update here:
https://github.com/curt-labs/API/commit/32e7a67fa2da45e316c43ba1132529a478794524
