### ISSUE TITLE
Jeep Accessories App Guide Download

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#182]
Jeep Accessories App Guide downloads incorrect app guide.
Needs to be pointing to the Jeep Accessories file on the FTP.

/Vendor Login Files/masterlibrary/01resources/appguides/ARIES/Jeep Accessories.xlsx
/Vendor Login Files/masterlibrary/01resources/appguides/ARIES/Jeep Accessories.pdf

**Comment by ninnemana** [comment]
Can we go live with https://github.com/aries-auto/ariesautomotive/issues/143 and solve this forever?

**Comment by DavidVaini** [comment]
we went live with #143 so we should be good, closing issue.
