### ISSUE TITLE
Aries App guides - StyleGuard Floor Liners 

### ISSUE THREAD

**Issue by 1brandeja5** [aries-auto/ariesautomotive#184]
It appears it is missing item numbers:
![image](https://cloud.githubusercontent.com/assets/15163363/17987186/3037c7ee-6ae4-11e6-82da-9bc1668d0efd.png)

**Comment by ninnemana** [comment]
Feature: use the lookup.


![](http://1.media.collegehumor.cvcdn.com/84/45/b5d32f89ced994e0d5fa58f0a0478df0.gif)

**Comment by ninnemana** [comment]
It looks like the product matching does everything based off the `finish` attribute, which works for everything **EXCEPT** floor liners. Floor liners will need to be handled with the `color` attribute. The way it was done previously was based off a string search of `floor liner` in the collection name.

```javascript
if (collectionName.toLowerCase().index('floor liner') !== -1) {
   return getByColor();
}

return getByFinish();
```

https://github.com/aries-auto/ariesautomotive/blob/master/src/components/AppGuides/AppGuide/AppGuide.js
