### ISSUE TITLE
Buy Online Sort Order

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#185]
ARIES "where to buy online" is not randomizing dealers. It has them listed alphabetically.
 Please make them random when refreshing page.

![image](https://cloud.githubusercontent.com/assets/6673274/18133421/2777aa86-6f60-11e6-831b-ee67dc52dae6.png)

**Comment by DavidVaini** [comment]
fixed with this commit:
https://github.com/aries-auto/ariesautomotive/commit/a68b605eda419dec93d62ad412126938716bccd0
