### ISSUE TITLE
2055130 Not Populating in Look Up Results

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#186]
Did a look up on the ARIES site for 2017 Honda Ridgeline. 
The VersaTrac Brackets don't populate in the results.
They are in the Godzilla DB. 
![image](https://cloud.githubusercontent.com/assets/11978902/18144154/c9e94ca0-6f8a-11e6-9492-135a6d175ef0.png)

We are releasing these parts tomorrow. it'd be great if it could be populating by then.

**Comment by 1brandeja5** [comment]
@mcrandell disregard my email, I should have looked here first.  This is because the brackets are associated to both categories - if you look at the ridgestep category, the brackets are there

We need to figure out some new logic to make this work.

**Comment by DavidVaini** [comment]
this is a duplicate issue and was fixed with my commit here:
https://github.com/curt-labs/API/commit/32e7a67fa2da45e316c43ba1132529a478794524
