### ISSUE TITLE
2055152 Not Populating in Look Up

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#187]
VersaTrac bracket 2055152 isn't populating in look up results for the following applications.
2015 Toyota Tacoma Crew Cab
2016 Toyota Tacoma Crew Cab
I can see the part in the godzilla db.
![image](https://cloud.githubusercontent.com/assets/11978902/18144198/0805a29a-6f8b-11e6-9df0-6f4c3761077a.png)
![image](https://cloud.githubusercontent.com/assets/11978902/18144204/0fd8f9ea-6f8b-11e6-805f-8c8aa3f7077f.png)

We are releasing these parts tomorrow, it'd be great if we could get them to populate by then.

**Comment by 1brandeja5** [comment]
Same issue as #186

**Comment by DavidVaini** [comment]
fixed with this commit:
https://github.com/curt-labs/API/commit/32e7a67fa2da45e316c43ba1132529a478794524
