### ISSUE TITLE
Online eTailer not showing up.

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#188]
UniqueAutoDepot.com not showing up on ARIES where to buy online as Gold.

![image](https://cloud.githubusercontent.com/assets/6673274/18181770/7cf8b642-7052-11e6-9c56-7173142f693e.png)

**Comment by DavidVaini** [comment]
Show Website on Where To Buy was set to false, I used the Admin to set it to true, it showed up.

The Buy Online tab needs a website after all that is the purpose of the buy online tab (to link to their website so you can buy online)
