### ISSUE TITLE
ARIES Dealer Portal App Guide Page

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#189]
The application guides page in the Dealer Portal is outdated. It should reflect exactly what we have on the ARIES site. Is there a way we could synchronize the two? If nothing else, we could just redirect the link to the ariesautomotive.com page.

**Comment by ninnemana** [comment]
You have the keys: http://admin.curtmfg.com/website/content/74

**Comment by aaronrodgersmoustache** [comment]
I'm not able to make it a priority right now. How do I just make the menu button a link to the ariesautomotive.com app guide page?

**Comment by ninnemana** [comment]
I don't really think we should be sending them to a different site just to download some files, could be confusing. One day we could build a dynamic app guide page in the dealer portal, or one day it might not be a thing....

**Comment by DavidVaini** [comment]
So I created a dynamic app guide page for the dealer portal, I will be publishing it tomorrow morning.

https://github.com/aries-auto/dealers/pull/107

**Comment by DavidVaini** [comment]
the new dynamic app guides page is now live:
http://dealers.ariesautomotive.com/appguides

**Comment by aaronrodgersmoustache** [comment]
Thank you! You're the man.
