### ISSUE TITLE
Envision Support Badge

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#198]
Add badge to top right of product box that indicates the product being able to be added to the envision vehicle.

![image](https://cloud.githubusercontent.com/assets/187030/19326570/b0da701e-9090-11e6-96fe-750ae2be568f.png)

**Comment by ninnemana** [comment]
There is a bug where if the product title is long enough, but the badge overlaps the part number. Let's add some padding to the title to prevent overlap.

![image](https://cloud.githubusercontent.com/assets/187030/19781134/9a7f06d6-9c4d-11e6-99e8-c760217a88a9.png)

**Comment by baseigneurie** [comment]
Fixed: https://github.com/aries-auto/ariesautomotive/commit/f2f1631c9447ce9a8782f88043b39fd20c4e245c
