### ISSUE TITLE
Vehicle Lookup Cache

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#199]
When a lookup is submitted `/vehicle/2015/Ford/Fusion`, let's store the vehicle in a cached state so it can be re-used across the site.

If there is a cached vehicle the lookup component should render the cached vehicles `Year Make Model` as a string in place of the `<select>` statements with a `reset` button.

**Comment by DavidVaini** [comment]
I recently got it working, demo can be seen here:
http://xhr-vehiclecache-dot-aries-auto.appspot.com/

I am still doing some testing, so please take a look and let me know if you want any changes.

**Comment by DavidVaini** [comment]
went ahead and merged in the vehicle cache into the xhr sourcing branch.
https://github.com/aries-auto/ariesautomotive/compare/32b0451f7b2c...887b8f56a591
