### ISSUE TITLE
Browser Back Error

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#20]
Clicking the back button on the browser brings me all the way back to the ARIES homepage even though I've clicked through a number of pages. For example, when the back button should bring me from the product detail page back to the product selection page, it brings me all the way to the homepage instead. I haven't tried this on any of the other ARIES pages, but I have noticed it on several product detail pages.

**Comment by DavidVaini** [comment]
Is anyone able to replicate this? I have tried on my machine with no avail.

**Comment by DavidVaini** [comment]
@aaronrodgersmoustache  sent me an email saying, that he tried to replicate the issue on his computer again and couldn't.

Does anyone know anyone else that had this issue?

**Comment by mickelsonm** [comment]
I would talk to Chris...if this is no longer an issue for him, then it would probably be a safe bet to close.

**Comment by DavidVaini** [comment]
@cowan14  is not able to replicate it either, I am going to go ahead and close this issue for now.

**Comment by ninnemana** [comment]
Kyle was experiencing this

**Comment by DavidVaini** [comment]
I talked to Kyle as well and it seems fixed for him.
