### ISSUE TITLE
Category Page for Cached Vehicle

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#200]
If there is a vehicle in cache, utilize this year/make/model to query the lookup and display any product that data is associated to the current category and vehicle.

We should be able to utilize a lot of the components from the new lookup design to make this work easily.

This is dependent on https://github.com/aries-auto/ariesautomotive/issues/199

**Comment by baseigneurie** [comment]
Added with commits:
https://github.com/aries-auto/ariesautomotive/commit/fa0b5db159877fb8214ce1047d99033ccd20db4d
https://github.com/aries-auto/ariesautomotive/commit/800ff85e243d11f7431c06f992d790ce2721c175

**Comment by baseigneurie** [comment]
I noticed once the changes were merged in with with the` luverne-envision `branch that some of the categories would register as having parts (by displaying the Your Vehicle Parts title) but wouldn't show the drop down selections. I'm looking into this now.

**Comment by baseigneurie** [comment]
Fixed: https://github.com/aries-auto/luverne/commit/ea2028743ec3c4984524d4a798d9bbfd5f407e18
