### ISSUE TITLE
2017 Ford F-350 not showing in look up

### ISSUE THREAD

**Issue by etimme** [aries-auto/ariesautomotive#204]
Recently we added 2017 Ford F-350 coverage to several ARIES parts. When using the vehicle look up the 2017 F-350 is not available to select. I can see 2017 on the part page and when looking in ARIES Applications in the admin. 

![image](https://cloud.githubusercontent.com/assets/16309519/19403201/1e4675bc-922b-11e6-8836-4ef57669697f.png)

![image](https://cloud.githubusercontent.com/assets/16309519/19403203/2626ea0a-922b-11e6-97b2-5a7b8098b902.png)

![image](https://cloud.githubusercontent.com/assets/16309519/19403211/369695ac-922b-11e6-93f4-a162348b2824.png)

**Comment by mcrandell** [comment]
Hey any update on this issue? 
The F-350 still doesn't populate, I'd like to have an update for Bauer this week.

**Comment by ninnemana** [comment]
This issue was moved to curt-labs/API#71
