### ISSUE TITLE
StyleGuard App Guide Page not Working

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#205]
Was informed by Jesse Bauer the StyleGuard application guide page doesn't work.
![image](https://cloud.githubusercontent.com/assets/11978902/19478655/0b05be96-9509-11e6-8087-045edfc0d200.png)

Let me know when it's corrected so i can let Bauer know.

Thanks,

**Comment by DavidVaini** [comment]
It turned out that XHR branch ( a different version of the website pointing at staging) was publish. This pointed to a different database with old data. I reverted back to the previous version and everything is looking good including the styleguard application guide working.
