### ISSUE TITLE
2004-2009 Lexus RX350 Not Populating in Look up

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#207]
Received email from Jesse Bauer stating 04-09 Lexus RX350 Non-Hybrid isn't populating in look up.
Data is in Godzilla DB
![image](https://cloud.githubusercontent.com/assets/11978902/19534554/dd0fe2b2-9609-11e6-9aea-e0437c14322c.png)

I did forward the email to Alex.

**Comment by ninnemana** [comment]
Duplicate of https://github.com/curt-labs/API/issues/71
