### ISSUE TITLE
Repeat Images

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#21]
Several of the product pages have repeated images.
![aries repeat images](https://cloud.githubusercontent.com/assets/11280480/6603527/cd8e352a-c7f0-11e4-997c-efb977170ab8.PNG)

**Comment by DavidVaini** [comment]
It is because the images are in there twice for that part:
http://107.178.250.64/product/2010051/images

Remove the duplicates, clear part cache/ part-image cache and they will not show up twice.

**Comment by ninnemana** [comment]
Boom, I was just about the add the same comment.
