### ISSUE TITLE
Jeep Accessories - 2000 Jeep Wrangler

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#210]
When you lookup a  `2000 Jeep Wrangler` and click on the `Jeep Accessories` category, you should be presented with SKU `#15600TW`, but no results appear. Couple problems here:

1. It should show that product.
2. It shouldn't show a category, if it's not going to display the products.

![image](https://cloud.githubusercontent.com/assets/187030/19602835/6438acc2-9774-11e6-9a0f-90c945ed648a.png)

**Comment by baseigneurie** [comment]
Fixed - https://github.com/aries-auto/ariesautomotive/commit/399b4a22193995408439a9d1ee6c68ed5d3ebf15
