### ISSUE TITLE
ARIES lookup makes calls to Luverne API

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#211]
ARIES shouldn't be requesting vehicle data from the `/luverne/vehicle` endpoint.

![image](https://cloud.githubusercontent.com/assets/187030/19602895/98586de4-9774-11e6-869a-dc98cc529833.png)

**Comment by ninnemana** [comment]
![image](https://cloud.githubusercontent.com/assets/187030/19603736/cc58247e-9777-11e6-987a-38454ef6f20c.png)
 1.5s on render time.....OUCH.

**Comment by baseigneurie** [comment]
No longer fetching luverne vehicle on Aries.

![screen shot 2016-10-21 at 10 32 25 am](https://cloud.githubusercontent.com/assets/7674939/19604177/cbc48df2-9779-11e6-9ff3-4eb8b808b40a.png)
