### ISSUE TITLE
Changing Vehicle

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#212]
I looked up a vehicle `2013 Ford F-350` and then clicked `Change`. Entered `2000 Jeep Wranger` it updated the vehicle string, converted `View Parts` to `Change`, didn't navigate the page to `/vehicle/2000/Jeep/Wrangler`. The product results updated to `2000 Jeep Wrangler` products, but envision wasn't updated.

It needs to call `Location.push` on the route for the new vehicle.

**Comment by DavidVaini** [comment]
fixed with this commit:
https://github.com/aries-auto/ariesautomotive/commit/dc25fa459605a24d1de48327816b81eb69cc6754

**Comment by DavidVaini** [comment]
when a direct link to a vehicle is hit, we want to create a cookie based off the input.

**Comment by DavidVaini** [comment]
fixed with these commits:
https://github.com/aries-auto/ariesautomotive/commit/c3f8c6b6125e386b2ead7afa3ca87af2c1786cb8
https://github.com/aries-auto/ariesautomotive/commit/8221385ec64ce3ea95f533233e766f95576ddcdf
