### ISSUE TITLE
Changing Style in Product Category

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#213]
When you toggle the `Style` dropdown, from a previously selected value, it's not updating the product list.

**Comment by baseigneurie** [comment]
Turns out on style update if there were the number of results coming back from the fetch was the same as the current state, it wouldn't update. Fixed that.

https://github.com/aries-auto/ariesautomotive/commit/f23a5d2e990c79bda99d346fc4662996b0c2a0e1
