### ISSUE TITLE
Verify Form Submissions

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#219]
Let's make sure form submissions still work on production.

**Comment by DavidVaini** [comment]
fixed with this commit:
https://github.com/aries-auto/ariesautomotive/commit/c65e834d0b7c8819ceac51d790280040d3596190

not published yet.

**Comment by DavidVaini** [comment]
published, filled out the form, waiting for response from Luverne customer support. Locally it worked when I had the contact receiver setup as myself.

**Comment by DavidVaini** [comment]
I temporarily changed the recipient email address on the database to my own email address, filled out the forms and received emails. I changed them back to customerservice@luvernetruck.com

Closing issue.
