### ISSUE TITLE
New Contact Us Hero for Luverne

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#220]
Use this hero image: https://storage.googleapis.com/luvere_site_content/Exterior%20-%20Luverne%20-%20Summer%20(4v1).jpg

Should probably be a config or something...

**Comment by DavidVaini** [comment]
fixed/updated with this commit:
https://github.com/aries-auto/ariesautomotive/commit/a0f36796a1d1b5913cc5242e089ed5c8a1d53add
