### ISSUE TITLE
575114-570717 - Luverne

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#221]
Should be visible under 2014 Chev Silv 2500 HD

http://luverne-truck.appspot.com/vehicle/2014/CHEVROLET/SILVERADO%202500HD

It comes back as a fitment option with the requirement of know box length, however box is not an attribute option under Mega Step
![image](https://cloud.githubusercontent.com/assets/187030/19737447/1a6d4554-9b79-11e6-8517-4664216a8021.png)

It is bound in the API: http://goapi.curtmfg.com/luverne/vehicle/2014/CHEVROLET/SILVERADO%202500HD?key=9300f7bc-2ca6-11e4-8758-42010af0fd79&brandID=4

**Comment by baseigneurie** [comment]
This is interesting. So I ran luverne locally and I was presented the option:
<img width="1354" alt="screen shot 2016-10-26 at 12 57 13 pm" src="https://cloud.githubusercontent.com/assets/7674939/19738278/6c9206d2-9b7c-11e6-9a30-92fdb4e8b3c6.png">

Then I checked it out in staging, with the same results:

http://luverne-envision-dot-luverne-truck.appspot.com/vehicle/2014/CHEVROLET/SILVERADO%202500HD

<img width="1353" alt="screen shot 2016-10-26 at 1 01 24 pm" src="https://cloud.githubusercontent.com/assets/7674939/19738302/7db057d4-9b7c-11e6-8ad3-f5e49880bfc7.png">

Could it be an issue with the data on luverne-truck.appspot.com?

**Comment by baseigneurie** [comment]
So I noticed the luverne-truck.appspot.com category is missing the fitment of box for that category.

<img width="318" alt="screen shot 2016-10-26 at 1 35 34 pm" src="https://cloud.githubusercontent.com/assets/7674939/19739916/5a5c0520-9b82-11e6-9fe6-25f82798888f.png">

But my local version, and the luverne-envision-dot-luverne-truck.appspot.com DO include it

<img width="280" alt="screen shot 2016-10-26 at 1 35 50 pm" src="https://cloud.githubusercontent.com/assets/7674939/19739944/71fac16c-9b82-11e6-8b6a-66e4c86cac83.png">

**Comment by DavidVaini** [comment]
should be fixed with this commit:
https://github.com/curt-labs/API/commit/fccdcae206493db8b34e3048e1b5c6a68584162b
