### ISSUE TITLE
Can't Paginate Search Results

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#230]
Load more action on a search results page creates a JS error.

**Comment by DavidVaini** [comment]
turns out, there is no paging functionality in the search store/source, this will need to be added in order to page results.

**Comment by DavidVaini** [comment]
Paging functionality added with this commit:
https://github.com/aries-auto/ariesautomotive/commit/b086e1930bf46b11f5bb1330f72301ab192b4a92
