### ISSUE TITLE
Changing Vehicle Should Clear `Parts List`

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#231]
If you follow the flow below, you will clear the vehicle from the `<Lookup />` but the `Parts List` doesn't get cleared out. It should clear the `Parts List`, check you click the `Change` action in the `<Lookup />`.

1. Lookup vehicle: http://ariesautomotive.com/vehicle/2014/CHEVROLET/SILVERADO%201500
2. Add `6" Oval Side Bars` -> `Double Cab (Rocker Panel Mount)` -> `B2875`
3. Click `CHANGE`

![image](https://cloud.githubusercontent.com/assets/187030/20156258/3b5cd0e6-a695-11e6-9132-a33de1f49ef4.png)

**Comment by baseigneurie** [comment]
Fixed: https://github.com/aries-auto/ariesautomotive/commit/d131b67ec800b316b82adb3fa9d29f09849f4ab3
