### ISSUE TITLE
Homepage Content Updates

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#233]
Martin has requested a few video/image updates to the homepage.

He'd like to swap out the YouTube videos with the following:
Top Video: https://www.youtube.com/watch?v=RsH5vaVF4w4
Second Video: https://www.youtube.com/watch?v=8RaC5j5UT5w

He would also like to replace the "Never Fear the Uncertain Road" with the following image and link it to `/category/342/AdvantEDGE%205.5%22%20Bull%20Bars`. Since the image is currently 7.7MB, can we optimize first? If the optimization isn't going to help the file size, maybe we can see about using a black/white variation.

![ig1a1705](https://cloud.githubusercontent.com/assets/187030/20355683/c53d069e-abe7-11e6-9463-39b31a772662.jpg)

**Comment by baseigneurie** [comment]
Updated: https://github.com/aries-auto/ariesautomotive/commit/3ad54df5ab8bd84358113a843562ef427ab552ca
