### ISSUE TITLE
New Parts not appearing on ARIES site

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#239]
I'm releasing 5 seat defenders for ARIES
3147-01
3147-09
3147-18
3147-20
3149-09

They were released to the admin from product desk last week. They are status 800 in XA and the admin.
But they don't show up in the search or the direct link (www.ariesautomotive.com/part/3147-01) dont work.

![image](https://cloud.githubusercontent.com/assets/11978902/20724894/a6c15af0-b635-11e6-8061-86e8f500a7a2.png)

**Comment by DavidVaini** [comment]
talked to @mcrandell  and I was able to index these parts manually by  hitting the /debug endpoint. These 5 parts are now into the system and show up on the website. I created a separate issue in regards to the indexing not working. Closing this issue.
