### ISSUE TITLE
Smaller Text on Listing Page

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#24]
Could we make the font for the attributes on the product listing page smaller? If the font were just a little smaller, the text wouldn't wrap, and I think it would look a lot better. We could also probably widen the area for the text. There is quite a bit of space after the cutoff point for the wrap.

![aries listing page text size](https://cloud.githubusercontent.com/assets/11280480/6926780/31c43fb8-d7ae-11e4-8309-2dbd0a6422fb.PNG)

**Comment by DavidVaini** [comment]
added with this commit: 
https://github.com/aries-auto/ariesautomotive/commit/08f3627fc623ccc5f657f604a7e54babac5a71a9
and then this one
https://github.com/aries-auto/ariesautomotive/commit/84d5999d7f32d3e54295872c177eab31464dc983
