### ISSUE TITLE
App Guide Won't Download

### ISSUE THREAD

**Issue by etimme** [aries-auto/ariesautomotive#240]
The 4" Oval Side Bar App Guide PDF and XLS will not download from this page. I did verify they are in the correct location on the FTP.

![image](https://cloud.githubusercontent.com/assets/16309519/20852762/3513989e-b8ad-11e6-97cb-2bb2467c735c.png)

The 3" Side Bar App Guide is gone from here. I verified this one is also on the FTP in the correct location.

![image](https://cloud.githubusercontent.com/assets/16309519/20852785/52b82e64-b8ad-11e6-9cd7-8a0b91f875bb.png)

**Comment by mcrandell** [comment]
Here is what is currently assigned in the admin:
![image](https://cloud.githubusercontent.com/assets/11978902/20901764/aae3cd52-baf9-11e6-82e0-3090be55f157.png)


//www.curtmfg.com/masterlibrary/01resources/appguides/ARIES%204%20IN%20OVAL%20SIDE%20BARS%20App%20Guide.pdf

//www.curtmfg.com/masterlibrary/01resources/appguides/ARIES%204%20IN%20OVAL%20SIDE%20BARS%20App%20Guide.xlsx

**Comment by ninnemana** [comment]
I think the PDF needs to be `//www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/ARIES%204%20IN%20OVAL%20SIDE%20BARS%20App%20Guide.pdf` and the XLS `//www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/ARIES%204%2520IN%2520OVAL%2520SIDE%2520BARS%2520App%2520Guide.xlsx`. It must be including some weird characters in how you're copying/pasting between the admin and other tool.

It looks like the 3" Side Bars aren't listed as an app guide in the admin anymore. If it needs to be in there, someone will have to re-create it in the admin.

![image](https://cloud.githubusercontent.com/assets/187030/20938262/ffe55f58-bbaf-11e6-9eff-33e3f41224a1.png)
