### ISSUE TITLE
Broken Image for Styleguard Floor Liners

### ISSUE THREAD

**Issue by shakilcfg** [aries-auto/ariesautomotive#244]
Hi Chris, 

 I wanted to report a  broken image in the landing page for Styleguard Floor liners. 
http://www.ariesautomotive.com/part/BM03711502
The screenshot is below for your reference.

![aries-broken-image](https://cloud.githubusercontent.com/assets/23505034/20948036/778bb4b8-bbd7-11e6-95ee-78b3d3b317b6.png)

Let me know if you have any questions.

Thanks

Shakil

**Comment by cowan14** [comment]
Not exactly sure what happened with this one. Image folder was missing from FTP. Re-uploaded images and image links are working now.

**Comment by shakilcfg** [comment]
Np. Thanks for your help!
