### ISSUE TITLE
P35700 & P35800 Not Populating in ARIES Search

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#246]
It was brought to my attention from Joe Ripienski that parts P35700 & P35800 don't populate in the ARIES search.
Both parts are set up correctly in product desk and have been integrated into the Admin.

**Comment by DavidVaini** [comment]
Both of these products are marked as status 600  ( Not Yet Available ) in the admin, do we want Not Yet Available products to be available in the search?

**Comment by DavidVaini** [comment]
I looked and we are returning these parts in the search:
http://ariesautomotive.com/search/P35800
http://ariesautomotive.com/search/P35700

Must have just taken a little longer in the message queue?

**Comment by mcrandell** [comment]
I was able to search the P35800 in an incognito window. 
The P35700 still returned zero results in an incognito windwo.

**Comment by dgallegos** [comment]
@mcrandell I see product 35800 showing up as status 910 and P35700 as status 600.

Should P35700 be status 910 as well?

**Comment by ninnemana** [comment]
Seems there's a disconnect between ProductDesk and MySQL. Status 910 in ProductDesk and 600 in MySQL, that'll cause it.

**Comment by 1brandeja5** [comment]
This has been fixed.

**Comment by dgallegos** [comment]
http://ariesautomotive.com/search/P35700 now appears.
