### ISSUE TITLE
ARIES 2017 Catalog on Home Page

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#249]
Please remove the ARIES Interior and ARIES Jeep Catalogs from the home page.

Replace with the ARIES "2017 Catalog" to the home page. See attached screenshot of placement.

Links for the catalog cover thumbnail and catalog pdf are below:

https://storage.googleapis.com/aries_catalog/ARIES_2017_Cover.jpg

https://storage.googleapis.com/aries_catalog/ARIES%202017%20Catalog.pdf

![2017 catalog placement](https://cloud.githubusercontent.com/assets/6673274/21229620/d96044a2-c2a7-11e6-9358-dbd42a5d0e9f.JPG)

**Comment by ninnemana** [comment]
Fixed https://github.com/aries-auto/ariesautomotive/pull/252
