### ISSUE TITLE
ARIES Search Results with "-2"

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#26]
Whenever you search anything with "-2" at the end, it seems like you get all parts with the "-2" at the end; that is, stainless steel parts. It should only show parts with the full number you searched.
![aries site search results](https://cloud.githubusercontent.com/assets/11280480/6970683/a89d0072-d93c-11e4-8396-e6372a1e4a20.PNG)

**Comment by ninnemana** [comment]
I think this part simply didn't get put in the search index. Once I added it to the index, everything is returning just fine. Also if you were to search for one of the `-2` items that were returned in the above screenshot, `203014-2` for example, comes back as expected in search.
