### ISSUE TITLE
Look Up Not Populating

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#262]
Was informed by Jesse Bauer in Product Management that the ARIES look up isnt working properly.
When you look up a 2016 Chevrolet Colorado you only get results for a 4" Oval Side Bar and StylGuards.
![image](https://cloud.githubusercontent.com/assets/11978902/22339373/603db554-e3af-11e6-8328-d4c54b9f3b4e.png)

I looked for part 4088 (grille guard). I see it populated in the Godzilla data base:
![image](https://cloud.githubusercontent.com/assets/11978902/22339365/5aad2642-e3af-11e6-93e1-68377b22fa81.png)

Also when you go to the part page for 4088 it isn't displaying any application data:

![image](https://cloud.githubusercontent.com/assets/11978902/22339407/810f85f0-e3af-11e6-9f5b-3c2c6d41d903.png)

I'm thinking what ever is causing this issue is affecting other parts as well.

**Comment by mcrandell** [comment]
Another example has been brought to my attention.
The Cadillac Escalade ESV isn't populating on the look up.
I see in the Godzilla tool the data is there:
![image](https://cloud.githubusercontent.com/assets/11978902/22353364/a04a15da-e3e5-11e6-9a2a-1ae712a213f3.png)

**Comment by mcrandell** [comment]
Another example: Parts: 3066, 3066-2, P3066
Data is in Godzilla DB, not populating in look up ARIES site
![image](https://cloud.githubusercontent.com/assets/11978902/22385744/96f8cd1e-e499-11e6-9630-15894518f733.png)

**Comment by dgallegos** [comment]
Looking into this. Most likely our changes to App Guides affecting this.

**Comment by DavidVaini** [comment]
Cleared memcached, did lookup for 2016 Chevrolet Colorado and returned other categories. I agree with @dgallegos  it was probably the changes to app guides and/or a combination of that and caching.

**Comment by dgallegos** [comment]
@mcrandell can you verify this looks good to close?

**Comment by mcrandell** [comment]
@dgallegos and @DavidVaini the 2016 Colorado worked great, along with the 2016 Cadillac Escalade ESV.
The 2017 Ford F-150 still isn't returning any Grille Guards. I even tried the look up in incognito mode.

**Comment by DavidVaini** [comment]
update:

I took a look in the MongoDB application_data collection and noticed that the 2017 is not there. I will need to look at the CSV that was uploaded to see if it is in there or not.

**Comment by DavidVaini** [comment]
Update #2: I took a look at the CSV file from Product Desk and the 2017 is not in there. @mcrandell @1brandeja5

**Comment by mcrandell** [comment]
@DavidVaini Is the "manage applications" portion of Godzilla in the admin not an accurate representation of what is in the MongoDB anymore?

**Comment by DavidVaini** [comment]
Yes that is correct, I am referring to the CSV file from product desk. I thought you were in on the loop on this, but Alex made a change to the system where application data that feeds the lookup which is stored on MongoDB is now fed through a process that runs each night looking at a CSV file that is dumped from product desk and thats put on the FTP for us to scrape. @1brandeja5 is the one who setup the file.

**Comment by mcrandell** [comment]
I dropped a new CSV on the FTP on 2/2/17. 
I still dont see the 2017 Ford F-150 bringing up grille guards.

**Comment by DavidVaini** [comment]
Update: The script to take the CSV contents and put them on the website ran this weekend. With the new changes in the CSV file, the changes took affect and are now showing on the website.

http://ariesautomotive.com/vehicle/2017/FORD/F-150

**Comment by 1brandeja5** [comment]
Hi-
We still have the issue with the lookup not grouping correctly:
[cid:image001.png@01D28055.89AAE6E0]

Please let me know if you need more information.

Thanks,
Jesse

**Comment by DavidVaini** [comment]
@1brandeja5  yes, I will need more information. The original issue here every vehicle given is showing up correctly to the best of my knowledge.

What do you mean by "grouping"? Is this a separate issue?

**Comment by 1brandeja5** [comment]
sorry @DavidVaini - I meant to attach this image:

![image](https://cloud.githubusercontent.com/assets/15163363/22651591/3353e6b0-ec49-11e6-97c9-b705e83295da.png)

**Comment by 1brandeja5** [comment]
There is a sorting issue and a grouping issue.  It is not grouping the 2500 HD together and it is sorting the Suburban XL above the Silverado, and then more Suburban choices exist below the Silverado.

**Comment by DavidVaini** [comment]
ah, that is a separate issue that was not brought up previously, I will create a separate issue for it and tag you.
