### ISSUE TITLE
All Products Page - Bad Format

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#268]
It's probably a simple fix, but the all products page is a little goofed up. The 4" oval wheel-to-wheel side bars category is returning weird onto its own line.

http://www.ariesautomotive.com/category/

**Comment by aaronrodgersmoustache** [comment]
Also, I'm not sure why we're showing the app guides at the top of the page. It seems a little strange.

**Comment by shakilcfg** [comment]
Able to replicate the bad format in chrome. Adjusting css files and font to avoid overlaps. Tested mobile too.
