### ISSUE TITLE
Images Orderby on Homepage

### ISSUE THREAD

**Issue by mickelsonm** [aries-auto/ariesautomotive#27]
Per @cowan14 : There is an issue with which image is getting used on the homepage.

For example, for Part `3142-18` (Accessories->Seat Defenders):

After running the following query:
```sql
select pis.size,pi.sort,pi.height,pi.width,pi.path from PartImages as pi
join Part pa on pa.partID = pi.partID
join PartImageSizes as pis on pi.sizeID = pis.sizeID
where pa.oldPartNumber = '3142-18' order by pi.sort, pi.height
```

It reveals that the first Grande image (homepage filters on this) is `http://www.curtmfg.com/masterlibrary/01Aries/3142-18/images/3142-18_300x225_a.jpg`. Also, this is represented in the following API request: http://ariesautoapi.curtmfg.com/part/old/3142-18?key=883d4046-8b96-11e4-9475-42010af00d4e

But on the homepage, it is seeing `http://www.curtmfg.com/masterlibrary/01Aries/3142-18/images/3142-18_300x225_va.jpg` as being the first one.

**Comment by DavidVaini** [comment]
fixed with this commit:
https://github.com/aries-auto/ariesautomotive/commit/c1e3df4
