### ISSUE TITLE
Video Report

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#272]
trying to download a copy of ARIES video report in Dealer Portal......it was working last week. Have to hit "refresh" a bunch of times but it works eventually.  Now it is showing error "failed to retrive report preview/undefined"

**Comment by cowan14** [comment]
same thing happening in CURT Dealer Portal/Video Report

**Comment by DavidVaini** [comment]
I'm curious if this is a redis problem. If memory serves me right, the report data is stored in redis and it uses a redis key to pull down the report data. If so we are working on a redis fix.

**Comment by DavidVaini** [comment]
Video Reports are now working again. The issue was redis. It was trying to generate the report and then write it to redis to store that document. It failed to store the document. Redis is now working as intended and writes are not going to the master.
