### ISSUE TITLE
Insert new Part Attributes

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#29]
Remove all part attributes, except UPC for Aries products and import all valid (not empty) values from the attached [XLS](https://drive.google.com/file/d/0B-LWdDRP9ednQV93bVdWckdRMDg/view?usp=sharing).

/cc @aaronrodgersmoustache

**Comment by ninnemana** [comment]
Let's hold off on this until we have audited against what's currently in the database.

**Comment by DavidVaini** [comment]
Is this ever going to happen or have we decided not to?

**Comment by ninnemana** [comment]
April 21, I'm guessing it's out dated by now.
