### ISSUE TITLE
Category Page Text Wrap

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#30]
We are going to be adding an image to each of the category pages. The images will be the same size as the video on the floor liners page. I think we've discussed it before, but this would be a good time to address the text wrapping issue. Could we have the text on the category pages wrap around the video/image?
![aries web text wrap](https://cloud.githubusercontent.com/assets/11280480/7297970/1395b56c-e992-11e4-805a-16d4b34cd4fc.PNG)
Thank you.

**Comment by DavidVaini** [comment]
That content is actually edited in the Aries Admin through the WYSIWYG Editor. This can be done through the admin by going here:

http://admin.ariesautomotive.com/categories/347/content/311828

You should probably talk to Chris about editing this content. He is pretty familiar with how to use the editor.
