### ISSUE TITLE
site search not working for interior parts

### ISSUE THREAD

**Issue by pmcginley** [aries-auto/ariesautomotive#31]
Ty03421509

Search does not find it.

I can find it if I lookup a 2005 toyota prius

![image](https://cloud.githubusercontent.com/assets/259677/7392647/bfaa81a0-ee4e-11e4-942f-7e88b11a2bdd.png)

**Comment by ninnemana** [comment]
Never got indexed, clicking `Save` on http://admin.ariesautomotive.com/product/2806161 fixed it.
