### ISSUE TITLE
Torrance Address Typo

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#33]
The Torrance warehouse address should be `23935 Madison St.`, not `23292 Madison St.`

**Comment by DavidVaini** [comment]
fixed with this commit (master):https://github.com/aries-auto/ariesautomotive/commit/65b7ac8bbb4e08843107c3ef81ffa44d50b1776f
and this commit (godzilla):
https://github.com/aries-auto/ariesautomotive/commit/0b6fc51232ce070cabefa9bf9e45ab35fd944b3a
