### ISSUE TITLE
Add Application Guide via Category

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#34]
Enumerate out the applications that are tied to a particular product category. "Old Fit Guide".

**Comment by DavidVaini** [comment]
Do you know how you want it presented?  I guess I don't know what you mean by "Old Fit Guide"?

I figure it would be something like this:
```html
<h2>3 IN ROUND SIDE BARS</h2>
<ul>
<li>Application</li>
<li>Application 2</li>
<li>Etc..</li>
</ul>
<h2>BULL BARS</h2>
<ul>
<li>Application</li>
<li>Application 2</li>
<li>Etc..</li>
</ul>
```

Or do you mean like this, but instead of Select a Mount, you start with your categories?:
http://www.curtmfg.com/HitchLookup/

**Comment by ninnemana** [comment]
Say I click to see the Bull Bars applications, it should show something like the following:

| Part | Part Description | Year | Make | Model | 
| ------------- |-------------| -----| ---------- | ---------- | ---------- |
| 35-0000 | 3 In Bull Bar | 2010 | Ford | Explorer | All |
| 35-0000 | 3 In Bull Bar | 2010 | Ford | Explorer | All |
| 35-0000 | 3 In Bull Bar | 2010 | Ford | Explorer | All |
| 35-0000 | 3 In Bull Bar | 2010 | Ford | Explorer | All |
| 35-0000 | 3 In Bull Bar | 2010 | Ford | Explorer | All |
| 35-0000 | 3 In Bull Bar | 2010 | Ford | Explorer | All |

**Comment by DavidVaini** [comment]
This was created in a new branch called appguide:
https://github.com/aries-auto/ariesautomotive/tree/appguide

It is live here:
http://3.aries-auto.appspot.com/appguides

**Comment by pmcginley** [comment]
Clicking a row in the 'Bull Bars' application guide takes me to the 'View All Parts' page for that Application.

The Application page does not say 'Bull Bars'  for the Cadillac Escalade.  Can you add the name of the category that you came from to the header of the View All Parts page?
![image](https://cloud.githubusercontent.com/assets/259677/8342953/3be74474-1a96-11e5-820c-14ec663bba96.png)

![image](https://cloud.githubusercontent.com/assets/259677/8342967/531d3a36-1a96-11e5-9ba2-1ffd71352e3d.png)

**Comment by ninnemana** [comment]
Now let's try converting to year ranges...

**Comment by ninnemana** [comment]
Just waiting on the download links for each category and we'll be set.

**Comment by DavidVaini** [comment]
Are we still planing on this? It looks like the App Guides work..

**Comment by ninnemana** [comment]
Yes, still waiting on the download links, @mcrandell said that he will have them by EOB Wednesday.

**Comment by ninnemana** [comment]
So all the Application Guide links aren't changing except the Bull Bars and Grille Guards. Now that they've been merged the new App Guides are below.

Grille Guards: 
PDF - http://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Merged%Grille%20Guards.pdf
XLS - http://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Merged%20Grille%20Guards.xlsx

Bull Bars: 

PDF - http://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Merged%20Bull%20Bars.pdf
XLS - http://www.curtmfg.com/masterlibrary/01resources/appguides/ARIES/Merged%20Bull%20Bars.xlsx

**Comment by DavidVaini** [comment]
I added the pdf and xlsx files to each of the application guides with this commit:
https://github.com/aries-auto/ariesautomotive/commit/1977fad1c7c0499fdb012c4f537b345d4d9ccb43

**Comment by ninnemana** [comment]
Went live 55fcf589f8dc2cbb64933cdf7139bc24eca10b1a
