### ISSUE TITLE
Contact Page - Become a Dealer option

### ISSUE THREAD

**Issue by DavidVaini** [aries-auto/ariesautomotive#35]
Right now if you go to the contact page and select "What would you like to contact us about?" and choose Become a Dealer, it should show a few more form fields for business name:

https://github.com/aries-auto/ariesautomotive/blob/master/src/app/controllers/contact/index.html#L28

looks like its checking for 15 when it should be checking for 51.

**Comment by DavidVaini** [comment]
I am going to use this as an introduction to the Aries Project for @TopShelfBullard since its a very simple change (changing from 15 to 51), it will be good for showing how to build the project and publish it.

**Comment by TopShelfBullard** [comment]
Issue closed with this commit:
https://github.com/aries-auto/ariesautomotive/commit/2fc5e02869f816260f42dd7de9db546ab9aacce6

**Comment by DavidVaini** [comment]
Congrats on your first commit, publish, and issue closing!
