### ISSUE TITLE
Missing Navigation

### ISSUE THREAD

**Issue by baseigneurie** [aries-auto/ariesautomotive#36]
While trying to build a working sitemap I noticed that when accessing the ariesautomotive.com site in IE9 there were no navigation menu items, just a link to the application guides. 

I had to test the site's hashbang URLs for the SEO audit, which is when I discovered this. I was running IE9 in a virtualbox instance of win 7.

**Comment by baseigneurie** [comment]
Screenshot for proof of issue

![screen shot 2015-06-29 at 11 14 58 am](https://cloud.githubusercontent.com/assets/7674939/8412672/eb74effa-1e50-11e5-98a8-7405a7a5009e.png)

**Comment by ninnemana** [comment]
Is the HTTP request failing?

**Comment by baseigneurie** [comment]
It appears so. It looks like this script is the one that supposed to insert the navbar, which as far as I can tell by IE9's dev tools it does complete the request.

![screen shot 2015-06-29 at 11 59 26 am](https://cloud.githubusercontent.com/assets/7674939/8413512/b5cb3070-1e56-11e5-8952-efcafdc34bac.png)
![screen shot 2015-06-29 at 12 01 42 pm](https://cloud.githubusercontent.com/assets/7674939/8413513/b8757452-1e56-11e5-87c1-6e57ffcd7c42.png)

**Comment by DavidVaini** [comment]
This must have been resolved at some point, I just looked on IE and it seems to be loading the navigation just fine.
