### ISSUE TITLE
Missing GlyphIcon Fonts

### ISSUE THREAD

**Issue by DavidVaini** [aries-auto/ariesautomotive#37]
GlyphIcons appear to be missing if you run the latest specified versions of dependancies.

If you run Bower Install and then try to build or serve the project, you will note that the glyph icons are missing are are replaced with an unknown character symbol (box)

**Comment by stinkyfingers** [comment]
There is a fix in place - relies on cdn. Broc will fix the dependencies first thing tomorrow probably.

**Comment by DavidVaini** [comment]
wow way to step up to the plate @baseigneurie

**Comment by baseigneurie** [comment]
What are dependencies?

**Comment by stinkyfingers** [comment]
I don't know. I'll hadoop up the proxy later.

**Comment by ninnemana** [comment]
Killed it 46f2d2d4a52523bfed47f51eae95f5b9946a7766

**Comment by baseigneurie** [comment]
David verified, the issue is not fixed. I deleted my local copy, pulled down the 'fixed' copy, updated bower/npm and then did a gulp serve and the glypicons were not present. David repeated the same steps and confirmed, the issue is not fixed.

**Comment by mickelsonm** [comment]
Thanks for verifying David.

**Comment by DavidVaini** [comment]
It breaks when I clear everything and try 3.3.5, when I clear everything and try 3.3.3 it works for me.

**Comment by baseigneurie** [comment]
Works now, must need 3.3.3 https://github.com/aries-auto/ariesautomotive/commit/5b37ec1
