### ISSUE TITLE
Re-Sync Aries Lookup Data

### ISSUE THREAD

**Issue by DavidVaini** [aries-auto/ariesautomotive#39]
Tim asked us to re-sync the Aries Lookup Data (godzilla) with some provided excel files. I will be working with Max today to get that updated.

**Comment by ninnemana** [comment]
https://github.com/aries-auto/appimport

**Comment by DavidVaini** [comment]
:+1: 
Also John made a CSV upload in GoAdmin

**Comment by DavidVaini** [comment]
[x] - Bull Bars
[x] - Grille Gaurds
[x] - 3 Inch Normal Round
[x] - 3 Inch Pro Series
[ ] - 4 inch oval
[ ] - 4 inch big step round
[ ] - 4 inch wheel to wheel oval
[ ] - 6 oval and mounting bracket
[ ] - floorliners
