### ISSUE TITLE
Update Application Guide PDF and Excel files to new format

### ISSUE THREAD

**Issue by DavidVaini** [aries-auto/ariesautomotive#40]
We got some data from Tim that is being used to re-sync the aires lookup and these application guides will use the formatted tab in those excel files.

**Comment by DavidVaini** [comment]
@cowan14

**Comment by ninnemana** [comment]
If it's not just a simple file replacement on the CDN it might not be worth it http://3.aries-auto.appspot.com/appguides.

**Comment by DavidVaini** [comment]
It is, It is just a slight content change. Tim just really wants to see these files up on the site so he feels that everything is "synced up". The only difference is the addition of a PDF. Also there is a category difference.

**Comment by DavidVaini** [comment]
Updated with this commit:
https://github.com/aries-auto/ariesautomotive/commit/32631f8
