### ISSUE TITLE
Accessibility Audit

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#41]
I ran an accessbility audit using Chrome DevTools and it came back with some things that should be fixed.

![image](https://cloud.githubusercontent.com/assets/187030/8804732/304f5c3e-2f93-11e5-9015-c8a47dea1bd9.png)

**Comment by ninnemana** [comment]
Any updates here?

**Comment by baseigneurie** [comment]
Working on getting this finished today.

**Comment by baseigneurie** [comment]
Checked again with live site, the only aria warnings present are from the embedded youtube elements which are not accessible. 

0fc645a01d03dc019ea223b1321705ec0fe57a9f
