### ISSUE TITLE
Where To Buy

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#43]
Implement a dealer locator. There currently is no data to support this, so we will be copying all CURT customers to be Aries customers as a temporary way to test the application until the GoLive.

**Comment by mickelsonm** [comment]
>>There currently is no data to support this

The list isn't comprehensive, nor is it probably up-to-date to the current customer base, but you can find quite a few on the old Aries Jeep website [here]( http://ariesjeep.com/dealerlocator/map.html).

So I call bullshit... :smile:

**Comment by ninnemana** [comment]
Below is the list of online retailers that should be listed. We will not use a hierarchy for displaying customers (Platinum, Gold, Silver). They will all be thrown into one list, being displayed in a random order, we don't want one customer always being the first one listed.


Customer
 

4 WHEEL ONLINE (40108401)
40108401
4wheelonline.com

AMAZON.COM VENDOR/DROPSHIP (40109701)
40109701
amazon.com

AUTO CUSTOMS, LLC. (40106701)
40106701
autocustoms.com

canadianhitches.ca
40178701
canadianhitches.ca

Etrailer.com
10206601
etrailer.com

Morris 4X4
40067701
jeep4x4center.com

ONYX ENTERPRISE (WOODVIEW AUTO ACC) (40074301)
40074301
carid.com

Quadratec
40079901
quadratec.com

REAL TRUCK.COM (40082201)
40082201
realtruck.com

REVEL ENTERPRISES (40083301)
40083301
autotrucktoys.com

RKG LLC (40125201)
40125201
radoauto.com

TCI LLC (40097101)
40097101
suspensionconnection.com

TheHitchStore.com (40141001)
40141001
thehitchstore.com

TURN 5 INC. (40168001)
40168001
extremeterrain.com

US AUTO PARTS NETWORK,INC (40130001)
40130001
jcwhitney.com

US AUTO PARTS NETWORK,INC (40130001)
40130002
stylintrucks.com

**Comment by ninnemana** [comment]
Below is the list of online retailers that should be listed. We will have two "tiers" of customers for the online section, Platinum (preferred) online dealers and the rest. Both lists should be randomized and shown in one list, the Platinum should be randomized and placed before the randomized list of the rest.

Also, we don't want to use the Customer Name field for the title of the customer, use their URL. So `Amazon` should be listed as `Amazon.com`


Customer
 

4 WHEEL ONLINE (40108401)
40108401
4wheelonline.com

AMAZON.COM VENDOR/DROPSHIP (40109701)
40109701
amazon.com

AUTO CUSTOMS, LLC. (40106701)
40106701
autocustoms.com

canadianhitches.ca
40178701
canadianhitches.ca

Etrailer.com
10206601
etrailer.com

Morris 4X4
40067701
jeep4x4center.com

ONYX ENTERPRISE (WOODVIEW AUTO ACC) (40074301)
40074301
carid.com

Quadratec
40079901
quadratec.com

REAL TRUCK.COM (40082201)
40082201
realtruck.com

REVEL ENTERPRISES (40083301)
40083301
autotrucktoys.com

RKG LLC (40125201)
40125201
radoauto.com

TCI LLC (40097101)
40097101
suspensionconnection.com

TheHitchStore.com (40141001)
40141001
thehitchstore.com

TURN 5 INC. (40168001)
40168001
extremeterrain.com

US AUTO PARTS NETWORK,INC (40130001)
40130001
jcwhitney.com

US AUTO PARTS NETWORK,INC (40130001)
40130002
stylintrucks.com

**Comment by ninnemana** [comment]
We also need to implement the use of the new map flag

![aries-where-to-buy-pin](https://cloud.githubusercontent.com/assets/187030/10110405/9d225eaa-6392-11e5-98ca-b8a1739e6750.png)

**Comment by DavidVaini** [comment]
I updated the random sorting and the two lists combined into one:
https://github.com/aries-auto/ariesautomotive/commit/9658f7d7ef65c3411bd94644dbc134a1193333a9

Now all that is left is adding the flag

**Comment by DavidVaini** [comment]
Map Icons are now the Aries Flag:
http://3.aries-auto.appspot.com/buy

And CURT ones are still the CURT ones:
http://www.curtmfg.com/wheretobuy

**Comment by ninnemana** [comment]
@ladelman provided us with the necessary dealer information for local and online. 


[WHERE TO BUY FINAL - BRICK & MORTAR AND ECOM UPDATED.xlsx](https://github.com/aries-auto/ariesautomotive/files/4080/WHERE.TO.BUY.FINAL.-.BRICK.MORTAR.AND.ECOM.UPDATED.xlsx)

There is also data on designated sales representative, which got me to thinking that the sales representative data for customers isn't brand specific, which happens to be the case. From my understanding, one customer will have a sales rep for CURT and a different rep for ARIES. I'll have to confirm this before we worry about implementing any logic around it, of course.

**Comment by ninnemana** [comment]
Looks like the account numbers in the provided file don't match any customerID's in the database, perfect. I've reach out to @cowan14 to see if he can provide a cross reference, otherwise this could be painful.

**Comment by ladelman** [comment]
Seriously? From MAPICS? That is where I got the report from.

Lee Adelman
Vice President, eCommerce Sales
CURT Manufacturing & Aries Automotive

**Comment by ninnemana** [comment]
Ok, I'll have Chris see if he could expert a cross reference between the numbers.

For reference CHUX TRUX has account number 40113501 in the file, but in our system it's listed as 10395001.

**Comment by ladelman** [comment]
Should be both.

When I look at reports in the CUBE, it gives both numbers. Same thing in Webreports.

If this is not readily available to him, someone in IT for sure has the capability to cross it for you quickly.

Lee Adelman
Vice President, eCommerce Sales
CURT Manufacturing & Aries Automotive

**Comment by ladelman** [comment]
Alex,

The “rep information” was not necessarily the person responsible for the account. You can ignore that. That was just the source of the information. I should have deleted the column.

Lee Adelman
Vice President, eCommerce Sales
CURT Manufacturing & Aries Automotive

**Comment by ninnemana** [comment]
Tim is going to be providing a new file this afternoon with address information. Maybe we can unbind the customers from the Aries where to buy ahead of time?

**Comment by DavidVaini** [comment]
Just so we are clear, you mean removing all CustomerToBrand records of a brandID = 3

**Comment by DavidVaini** [comment]
@ninnemana  Just so we are clear, you mean removing all CustomerToBrand records of a brandID = 3

**Comment by ninnemana** [comment]
Went live 55fcf589f8dc2cbb64933cdf7139bc24eca10b1a
