### ISSUE TITLE
Latest News Page

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#46]
Need a "Latest News" press release landing page area similar to what we have on CURT.

with link added to footer of website under "COMNET" in the red colored font.

![image](https://cloud.githubusercontent.com/assets/6673274/9605824/87abc1c6-5085-11e5-8b1c-4d232d884df5.png)

**Comment by ninnemana** [comment]
Look what I found http://admin.ariesautomotive.com/landingpages

**Comment by ninnemana** [comment]
Thought this was just for the press release, re-opening..

**Comment by stinkyfingers** [comment]
Closed with 0922d2f.
