### ISSUE TITLE
iConfigurator

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#51]
Implement iConfigurator within the ARIES website. Let's add a link to it next to the `View Parts` button in the lookup and add a more graphical call to action above `DO IT WITH STYLE, DO IT WITH ARIES` on the homepage.

**Comment by DavidVaini** [comment]
I created a blank controller and the links to the controller and commented them out. Once we get the link to the visual configurator, then perhaps we can Iframe it in?

**Comment by DavidVaini** [comment]
Just waiting on I-Configurator.

**Comment by ninnemana** [comment]
This has been implemented.
