### ISSUE TITLE
Address Change

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#52]
![aries old address](https://cloud.githubusercontent.com/assets/11280480/10199770/231ae332-6768-11e5-86c1-2b41ae1d364a.PNG)

Please update the address to the CURT headquarters address.

6208 Industrial Drive
Eau Claire, WI 54701

**Comment by stinkyfingers** [comment]
Closed with f3e98875fed09d501c91bfbeafd8651ade7a4718.
