### ISSUE TITLE
Duplicate images being displayed on product details page

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#55]
Not sure if this widespread or not.

![image](https://cloud.githubusercontent.com/assets/6673274/10351629/2fd34404-6d10-11e5-823d-c0a159dca9a0.png)

**Comment by cowan14** [comment]
Seems to be duplicates on the Bumper Kits for sure

**Comment by baseigneurie** [comment]
The part was associated with an old part number (25600) in the data base. Wiped it out, Alex ran an import and now only the images associated to that part show up.
