### ISSUE TITLE
Add videos to product pages

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#56]
1.  http://admin.curtmfg.com/video/edit?msgType=newvideo&id=338#Generic

Add to all parts in http://www.ariesautomotive.com/category/331

2.  http://admin.curtmfg.com/video/edit?msgType=newvideo&id=339

Add to all parts in http://www.ariesautomotive.com/category/330

3.  http://admin.curtmfg.com/video/edit?msgType=newvideo&id=340

Add to all parts in http://www.ariesautomotive.com/category/332
 and
Add to all parts in http://www.ariesautomotive.com/category/333

**Comment by DavidVaini** [comment]
I added those videos to all the parts in those categories.
