### ISSUE TITLE
Add video to ARIES home page

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#58]
Please add the SEMA 2015 video to home page.  Put it where the current video is and slide that video under it so two videos will be on home page.

https://youtu.be/Idd2kVCbIkE

![image](https://cloud.githubusercontent.com/assets/6673274/10486145/358cba72-7253-11e5-9f69-cb9e7d40e6b8.png)

**Comment by baseigneurie** [comment]
Done - 301ec1db2c76f3cfbad71acfa7d790132224ef2c
