### ISSUE TITLE
ARIES Favicon

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#59]
Please update soon as possible please.

Icon folder on Graphics drive can be found here. 

W:\Departments\Marketing Graphics Photography\ARIES Website\ARIES Icons

![image](https://cloud.githubusercontent.com/assets/6673274/10517225/7ba1db4a-7321-11e5-8718-0f235b49c446.png)

**Comment by baseigneurie** [comment]
Done: 0e4b541c4fc479aa0ab69162450791563aae5135

**Comment by cowan14** [comment]
Thanks Broc!!

**Comment by mickelsonm** [comment]
@cowan14 Broc accepts beer as payment.

**Comment by cowan14** [comment]
What up Matt? How’s life and the new job?

**Comment by mickelsonm** [comment]
@cowan14 Things are going great, thanks. Hope you're doing well! Glad to see you're still keeping the programming team on their toes!
