### ISSUE TITLE
Page descriptions & links in different browser searches

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#62]
Page Descriptions are missing in Chrome/Google search and links are all broken.

![image](https://cloud.githubusercontent.com/assets/6673274/10526716/0b34dc8c-7352-11e5-944a-db595317d67d.png)

Page Descriptions show up in Internet Explorer 11/Bing search, but links are also broken.

![image](https://cloud.githubusercontent.com/assets/6673274/10526812/a0f8eb00-7352-11e5-9636-63009d2559fd.png)

**Comment by ninnemana** [comment]
https://www.google.com/webmasters/tools/sitelinks?hl=en&authuser=0&siteUrl=http://www.ariesautomotive.com/ Can't you fix the Google one's this way? I'm guessing Bing has something similar? Maybe @baseigneurie can use some of his Bing Rewards and fix it for us.

**Comment by baseigneurie** [comment]
Does this just choose which pages/links show up under the main search? I don't think this would make the description show up. I think I might have to fetch each page that's showing right now, and then submit to the index. But I can try it.

And I didn't want to say anything, but I spent all my bing points buying @ninnemana his own Microsoft Polo for a christmas present. Way to ruin the surprise.

**Comment by baseigneurie** [comment]
IF you look, after re-submitting there is no longer a [[pageDesc]] under the main site result, and now there are two more pages showing up in the sitelinks. So something is happening; is it possible it may take a little while to finish the crawl and update the results?

![screen shot 2015-10-16 at 10 01 53 am](https://cloud.githubusercontent.com/assets/7674939/10545168/f0705a8e-73ec-11e5-9fbb-ac597b5754a4.png)

**Comment by baseigneurie** [comment]
Alright, added some logic specifically for the google crawlers. This should hopefully update the descriptions and titles.

5ea8a14ffa8bfee093c8c7bc17b49ac4833554a5

**Comment by cowan14** [comment]
You da man!!! Thank you

**Comment by ninnemana** [comment]
Anyway we can verify other than sitting around and waiting?

**Comment by baseigneurie** [comment]
I get avfetch as Google and it came back with the empty template. I submitted that index to Google too. What else can we proactively do?

**Comment by baseigneurie** [comment]
From this morning: I can confirm that is the page decsription for Aries home page. It's working!

![screen shot 2015-11-05 at 8 41 49 am](https://cloud.githubusercontent.com/assets/7674939/10971289/2e2299c6-8399-11e5-92bb-4bf1e5a21999.png)

**Comment by cowan14** [comment]
Nice work Broccoli!

Sent from my iPhone 5s

On Nov 5, 2015, at 8:42 AM, Broc Seigneurie <notifications@github.com<mailto:notifications@github.com>> wrote:


From this morning: I can confirm that is the page decsription for Aries home page. It's working!

[screen shot 2015-11-05 at 8 41 49 am]<https://cloud.githubusercontent.com/assets/7674939/10971289/2e2299c6-8399-11e5-92bb-4bf1e5a21999.png>

-

**Comment by DavidVaini** [comment]
I just checked and this is still working, closing issue.

**Comment by ninnemana** [comment]
Should get much better after/if we deploy the node version
