### ISSUE TITLE
Page Title Populated

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#64]
We we're using `ngBind` to bind the `<title>` tag, which is great. However, most pages don't have the `$scope.pageTitle` assigned, there isn't even a global set in the root scope. Let's populate those, ok?

**Comment by DavidVaini** [comment]
closed with this commit: https://github.com/aries-auto/ariesautomotive/commit/9481c204273099e6be32263be6a2791aac7439e7
