### ISSUE TITLE
2015 Interior/Exterior catalogs don't open/download

### ISSUE THREAD

**Issue by stinkyfingers** [aries-auto/ariesautomotive#65]
http://storage.googleapis.com/aries-website/catalog-2015.pdf 
https://storage.googleapis.com/aries-website/9900005_Catalog_Interior_SFS_%20RA.pdf

Hope Miller says she can't download these and customers say they can't either. Links are on the ariesautomotive homepage. IE? They work fine in Chrome.

**Comment by DavidVaini** [comment]
![image](https://cloud.githubusercontent.com/assets/2159280/10669711/99e3c272-78a7-11e5-8915-b8452c87fe3e.png)
Issue is with the IE PDF viewer trying to open that file.

**Comment by DavidVaini** [comment]
It turns out that other files don't do this, I think it might be a compatibility setting in the PDF file itself. I talked to Chris about this and he told me to talk to Kacey.

**Comment by DavidVaini** [comment]
I just met with Kacey and she will re-save the file and get with Chris to re-upload the file and hopefully fix the issue.

**Comment by ninnemana** [comment]
@cowan14 has this been completed? If it has, will you test it validate that the problem was solved?

**Comment by cowan14** [comment]
Interior opens/downloads fine in Chrome and IE

Exterior opens/downloads fine in Chrome but hangs up in IE.  I re-uploaded PDF to cloud.

**Comment by DavidVaini** [comment]
We re-saved the file this time for web and re-uploaded the file. It now works in IE.
