### ISSUE TITLE
google webmaster site verification

### ISSUE THREAD

**Issue by mickelsonm** [aries-auto/ariesautomotive#66]
Hey guys! Lately, i've been researching Google Webmaster tools/site verification most of the day, which has left me kind of confused. 

In the source code for ARIES and CURT websites I saw:
```html
<!-- ARIES -->
<meta name="google-site-verification" content="2YAIw2si-iBLQTUFUuNXfq8u5uoXzTysfiBTsFntY00">

<!-- CURT -->
<meta name="google-site-verification" content="S1ZofeWSUu8VaM8vmlJ3WXKn4CbtlTtnovYUGGzbTNs" />
```
This tag is generated by Google and simply just put on the page. However, I have noticed that for different admins that this value changes when you want to re-verify the website.

So my question: Is @cowan14 the only admin that can verify these sites or can a second admin like @ninnemana also verify/see the same values that @cowan14 can see for a given property? Say you were looking at just ARIES...that meta tag would be the same for both admins inside of the webmaster tools? In my case, they aren't the same (hence the confusion).

Hope you guys can help and thanks in advance!

**Comment by ninnemana** [comment]
I think the key is just a temporary value that is used by Google to verify, I wouldn't be surprised it the valid was tied to a time interval that expired it. I think it's essentially a race between admins for who can verify the site first and once a key is used to verify the site, it has to stay there.

**Comment by mickelsonm** [comment]
There must be a reason they set it up that way, but who knows...the Google way often doesn't make much sense sometimes. I was hoping I had something setup wrong (I could at least fix that). Anyways, thanks for the feedback!

**Comment by mickelsonm** [comment]
@ninnemana Are you or any of your guys going to the Twin Cities Code Camp tomorrow?

**Comment by stinkyfingers** [comment]
I have underwear modeling all day tomorrow.

**Comment by ninnemana** [comment]
That's funny, I have a blind date with an underwear model tomorrow.

**Comment by mickelsonm** [comment]
Pretty classy guys :smirk:

**Comment by ninnemana** [comment]
@stinkyfingers he's jealous

**Comment by mickelsonm** [comment]
@ninnemana oh I am... @stinkyfingers just remember pics or it didn't happen!
