### ISSUE TITLE
ARIES Website Dropdown

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#70]
The front end dropdown menu is out of order. Right now, it lists 3" Pro Series and 3" Stealth at the bottom. These should go right after 3" bull bars.
![aries dropdown order - bull bars](https://cloud.githubusercontent.com/assets/11280480/11069101/1b36a384-879a-11e5-9581-68c919397eab.JPG)

**Comment by ninnemana** [comment]
I updated the `sort` field in the database for these categories. @aaronrodgersmoustache can you verify they are in the correct order now?

**Comment by aaronrodgersmoustache** [comment]
Yes, they are in the correct order. Thank you!
