### ISSUE TITLE
somebody should really make a directive out of the product boxes

### ISSUE THREAD

**Issue by stinkyfingers** [aries-auto/ariesautomotive#72]

**Comment by ninnemana** [comment]
#73 is better.

![image](https://cloud.githubusercontent.com/assets/187030/11098341/e58fcf14-8869-11e5-9d42-7a40edec191b.png)

**Comment by mickelsonm** [comment]
I think this matches John's feelings...

![use your words](http://www.quickmeme.com/img/49/49d5b5ba75433e79eee53c9a1133f569f9c99cb6893ddb48f1983332121f61fc.jpg)
