### ISSUE TITLE
Bullet Point Ordering

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#75]
I would like to be able to assign an order to the bullet points that appear on the product detail pages. Could you create this feature in the admin? It would be something that we could see and manipulate in the admin, but obviously wouldn't appear on the site. As it is currently, the newest bullet point is added to the top of the list, and many of the current bullet points are out of order. A good example is the Jeep tube doors.
![bullet point order](https://cloud.githubusercontent.com/assets/11280480/11155961/7c8f9e26-8a0e-11e5-95fe-9c73d8a44215.JPG)

**Comment by ninnemana** [comment]
Did 52e522f8d022df5dafbd287357537ef67bdce8fb fix this?

**Comment by baseigneurie** [comment]
No, that was for Part Attributes.

**Comment by ninnemana** [comment]
Oh whoops, I thought that's what those were.

**Comment by ninnemana** [comment]
Guess you have more work to do

**Comment by baseigneurie** [comment]
I was hoping you would say that.

**Comment by mickelsonm** [comment]
Look at @baseigneurie Go! @ninnemana better buy him :beers: if he gets this done before 5! :wink:

**Comment by baseigneurie** [comment]
This has been completed and Tim understands how to order bullets. Closing issue.

https://github.com/aries-auto/ariesautomotive/commit/5342e216f8e5ce09205b875b790272175a76fad2
