### ISSUE TITLE
Become a Dealer Fails

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#76]
Become a dealer submission is failing with the following error:

```
{"message":"Trouble getting contact type from Id.","messageDetails":"sql: no rows in result set","request_body":"","query_string":{"key":["883d4046-8b96-11e4-9475-42010af00d4e"]}}

```

**Comment by baseigneurie** [comment]
This is now fixed. Removed check for email server variable, changed to email address. 

ec306d800619cc50162503a939ca01e59de13c09
