### ISSUE TITLE
There be data problems yo!

### ISSUE THREAD

**Issue by mickelsonm** [aries-auto/ariesautomotive#77]
<img width="1347" alt="screen shot 2015-11-19 at 10 38 00 pm" src="https://cloud.githubusercontent.com/assets/5571416/11292073/45267cac-8f0e-11e5-84bc-826a701e1bfd.png">

That's on the live Aries Automotive website. The guy who does work on production gets to fix this right? :smirk:

**Comment by mickelsonm** [comment]
Here's another one for ya:

<img width="1324" alt="screen shot 2015-11-19 at 10 46 02 pm" src="https://cloud.githubusercontent.com/assets/5571416/11292136/5fa0104c-8f0f-11e5-82da-97e7c1d6c182.png">

**Comment by DavidVaini** [comment]
Thanks for the bug report, we appreciate your input. We will review this bug and fix it at our earliest convince.
