### ISSUE TITLE
Update testimonials and associated data

### ISSUE THREAD

**Issue by mickelsonm** [aries-auto/ariesautomotive#78]
It would be cool to read real testimonials, instead of the bullshit ones we made up for SEMA 2014.

Just saying...

**Comment by mickelsonm** [comment]
I vaguely remember the database structure for that...it should probably be updated to support business/company names, instead of just filling the first_name column or however that was setup. Front-end would need to be changed to reflect this as well (just a suggestion).

**Comment by DavidVaini** [comment]
Thanks for the suggestions, we appreciate your input. We will review these suggestions and get back to you at our earliest convince.

**Comment by ninnemana** [comment]
Tired of the open issue...probably won't happen soon.
