### ISSUE TITLE
Duplicate Vehicle Listings

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#8]
The "reverse" lookup on the part pages is showing duplicate vehicle configurations. Not entirely sure if this is an API bug of an application bug: http://aries-auto.appspot.com/part/S224045

![image](https://cloud.githubusercontent.com/assets/187030/5680593/e391acfe-97d4-11e4-8545-83d2bae90d83.png)

**Comment by DavidVaini** [comment]
http://aries-auto.appspot.com/part/AL231007

Yes, I noticed it too, it turns out that they are different vehicles, its just that the sub model and configurations are not being shown. (Application issue)

**Comment by ninnemana** [comment]
How do you guys want to approach the problem?

I see two options:

1. Figure out a good way to display n number of configurations.
2. Group vehicles based solely off Year/Make/Model/Submodel in the JS.

**Comment by DavidVaini** [comment]
I will be working on v2Mock today and making sure that all works with curtmfg, so it doesnt matter to me how John or Matt takes care of it :+1:

**Comment by ninnemana** [comment]
Closed with 8f4476e271cb2cd646f7ee20e1c733b3f96e7e90
