### ISSUE TITLE
Content Find and Replace

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#81]
With the 2016 ARIES catalog just coming to completion, there have been several updates to the ARIES content. Also, with Broc's new bullet ordering feature, all ARIES bullets need to be assigned a proper order. I would like to request a mass find and replace for the ARIES content in the admin, specifically for Short Descriptions, Bullets, HTMLDescriptions and CategoryBriefs for each part number.

The two attached spreadsheets list the find-and-replace content by part number. For each one, the first page is for the Short Descriptions and the second is for the other content pieces. You will notice in the "ARIES New Products - Find and Replace" spreadsheet that the second does not list a replacement content piece, but only a bullet order number. This is because it is for new products, and the content is already as it should be in the admin. Only the bullet order needs fixing because they became disorganized when Broc's tool was implemented.

Also, on the "ARIES Content - Mass Find and Replace" spreadsheet, there are a number of New Content Piece fields that say "[delete]" in red. As you can guess, these bullets should be deleted instead of replaced. There are also several Bullet Order fields that say "n/a". This is for non-bullet-type content pieces or to correspond to a deleted bullet.

These two spreadsheets are exhaustive in regards to relevant parts. The lists were generated by David Vaini only a few weeks ago. There should be no discrepancies between this data and that in the admin. That being said, let me know if there are any questions.

Thank you.
[ARIES Content - Mass Find and Replace.xlsx](https://github.com/aries-auto/ariesautomotive/files/47842/ARIES.Content.-.Mass.Find.and.Replace.xlsx)
[ARIES New Products - Find and Replace.xlsx](https://github.com/aries-auto/ariesautomotive/files/47843/ARIES.New.Products.-.Find.and.Replace.xlsx)

**Comment by ninnemana** [comment]
@mcrandell is going to review the content and get it loaded into his data today, hopefully tomorrow we should be able to execute and close.

**Comment by baseigneurie** [comment]
Excellent. I have all the queries and indexing script written and ready to go.

**Comment by mcrandell** [comment]
I reviewed the content from Tim Heinen and found many of the bullets were over the character limit. Sent files back to Tim for corrections. Once he has made corrections i'll update my data source and then have Broc make the changes.

**Comment by ninnemana** [comment]
This issue was moved to curt-labs/iapi#19
