### ISSUE TITLE
api key usage/security implication

### ISSUE THREAD

**Issue by mickelsonm** [aries-auto/ariesautomotive#82]
It's funny nobody raised a concern about security when putting the api key on the front-end, but here's the issue with doing so:

The way it stands now, a potential malicious user can take the api key out of the front-end and go looking at the api to see what kinds of other things they can do.

One way you could fix this is to create a proxy layer underneath your implementation. Your proxy layer would safely implement environment variables (from your deployment/manifest files) and these would be injected into your proxied endpoints. So instead of the front-end calling ```http://api.curtmfg.com/customer/prices?key=883d4046-8b96-11e4-9475-42010af00d4e``` your frontend would be changed to simply call the proxy (ex. ```/customer/prices```) would have your proxy do that for you.

It might look something like this if you kept using NodeJS:

```javascript
//This is your awesome web server with a proxy built in...
var request = require('request');

var listenPort = process.env.PORT||3000;
var apiKey = process.env.APIKEY;
var apiEndpoint = "http://goapi.curtmfg.com";

//todo: setup all your web server stuff/etc.

app.get('/customer/prices', function(req, res){
  request({
    //todo: you would probably create a helper method to construct the url used
    uri: apiEndpoint + "/customer/prices?key="+ apiKey 
      method: 'GET',
    }, function(err, resp, body) {
      if (err) {
        res.status(500).send(err);
      } else {
        res.json(resp.body);
      }
    });
});

//todo: more and more endpoints...

app.listen(listenPort, function(){
  console.log("listening on port:", listenPort);
});
```

The downside is you'd have to update all of your services to point to the proxy and on the proxy you would have to create all of these endpoints. The benefit is nobody other than your customer would know what their API key is. Also, in source control the key usage is only represented by an environment variable, so anybody looking through the code doesn't really have anything to go on past whatever endpoints were exposed on the proxy level.

Anyways...good luck!

**Comment by DavidVaini** [comment]
Thanks for the insight, we appreciate your input. We will review this issue and get back to you at our earliest convince.

**Comment by ninnemana** [comment]
A proxy would be the way to go for sensitive calls, which is why we have some endpoints that require a Private API key. The ARIES website for instance, uses a Public API key for all of the calls from the frontend. So, if someone were to look through the JS and find the key, they will only gain access to information that we are already putting out for everyone to see.
