### ISSUE TITLE
Where to buy - lookup

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#83]
remove auto complete to allow search by zip code to work correctly.

Example is zip code 33069

Pompano Beach, FL

Morris 4x4 Center

**Comment by ninnemana** [comment]
What happens you search for 33069 on Google Maps? I mean bummer than they have to type a couple more characters, but I think the auto complete is more beneficial than hindering. I mean if Google Maps, something that had a lot of user testing go into, works that way, chances are.....
