### ISSUE TITLE
Convert Lookup

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#85]
Let's convert the lookup to function like the lookup in the Dealer Portal. 

- Ask Year/Make/Model
- Persist in LocalStorage
- Present categories for Year/Make/Model
- Force style selections inside category tab.
- Display products for the Category/Year/Make/Model/Style

**Comment by ninnemana** [comment]
Began implementing in new-lookup brand: aries-auto/ariesautomotive@e48dbd22d29fd32ba126b4f1fd555344c3f6d2a1

**Comment by baseigneurie** [comment]
This has been implemented.
https://github.com/aries-auto/ariesautomotive/pull/98
