### ISSUE TITLE
ARIES Auto Accessories Guide

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#86]
I would like to be able to create an ARIES version of Understanding Towing. I have the content already; I just need a way to get it onto the site. It looks like my request for revamping Understanding Towing for CURT was turned down for now, but is this something we could do for ARIES?

**Comment by baseigneurie** [comment]
This sounds like a good idea, but this should be something Joe can bring up at the Idea Generation meeting today, and we can plan it out then. Until then, we'll close it until it's time to revisit.
