### ISSUE TITLE
Part Images Display Issue

### ISSUE THREAD

**Issue by DavidVaini** [aries-auto/ariesautomotive#9]
The part's images are not being displayed propperly. Some Parts on Category Listings are showing up with no images, however if you click on the part you can see the image on the part details page.

My guess It was because originally only one type of image was  in the data, its probably still only referencing that one type of photo.

**Comment by ninnemana** [comment]
Do you know of an example category?

**Comment by DavidVaini** [comment]
http://aries-auto.appspot.com/category/332

Part 15910 - No images being displayed until you click on the details for that part.
