### ISSUE TITLE
Catalog Updates on Home page

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#90]
Please update home page with links below.  Also change text to 2016 Exterior and Interior.

Exterior Image  - https://storage.googleapis.com/aries-website/ARIES-Exterior-Cover.png

Exterior Catalog - https://storage.googleapis.com/aries-website/2016-Exterior-Catalog.pdf

Interior Catalog - https://storage.googleapis.com/aries-website/2016-Interior-Catalog.pdf

![image](https://cloud.githubusercontent.com/assets/6673274/12052502/56bcace8-aed5-11e5-80d3-417f548febfe.png)

**Comment by baseigneurie** [comment]
This has been completed.

https://github.com/aries-auto/ariesautomotive/commit/f983af3462ee798f9414123eced35874cbdb47e5
