### ISSUE TITLE
2015 Toyota Camry All Floor Liner Look Up

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#91]
Floor Liner look up for 2015 Toyota Camry All pulls up the following.
![image](https://cloud.githubusercontent.com/assets/11978902/12117432/547ea8c2-b386-11e5-8537-8b26b0cd8024.png)

Checked the admin all "old part numbers" are entered, and parts have images.
Don't know what could be causing this.

**Comment by ninnemana** [comment]
They somehow got indexed twice, is it possible that those parts initially added with `1231121534, 1231121535, 1231121536, 1231121537` as the Part Numbers and then switched to `TY08711509, TY08721501, TY08721502, TY08721509`?

**Comment by mcrandell** [comment]
Very well could've happened, when we were having issues creating ARIES parts way back when.

**Comment by ninnemana** [comment]
Ok, maybe the fan out process needs to be reviewed. I'm guessing it's using the old part number to determine whether it's an update or an add, so if the old part number doesn't exist in MongoDB, it will execute an add.

**Comment by mcrandell** [comment]
Alex, 
Is there anything that data needs to do to get this resolved?

**Comment by ninnemana** [comment]
Nope. I resolved the Toyota Camry problem yesterday, I just wanted to leave the issue out there to remind us to look at what could cause this and how to prevent it from happening again.

**Comment by mcrandell** [comment]
Thanks
