### ISSUE TITLE
3 Inch Side Bar Content Update

### ISSUE THREAD

**Issue by mcrandell** [aries-auto/ariesautomotive#92]
Travis Machler brought to my attention that all the 3 IN Round Sidebars (Normal and Pro Series) have a bullet and part of the category brief stating it is an Easy No Drill application.
Only certain parts in these categories are actually No Drill. He wants us to remove the bullet and the category brief where it states the part is No Drill.

Not sure if there is a way you can mass delete these content parts.

Thanks

**Comment by aaronrodgersmoustache** [comment]
If we are planning to do a mass clearing of the content and upload new content, then we can fix this issue at the same time. I will make the appropriate changes in the content master.

**Comment by mcrandell** [comment]
Thats good it's being removed from the content master, but i'm unsure of an ETA when we will be uploading this. So i'm unsure of how long we want to leave the incorrect content on the web.

**Comment by DavidVaini** [comment]
The Bullets are easy, just gotta remove them. The CategoryBrief's are trickier. Here is an example of a CategoryBrief with the zero drilling required:

```
<p> <strong>Special E-coat finish</strong></p> <p> Carbon steel side bars receive a special E-coat to add even more resistance against peeling, chipping and scratching.</p> <p> <strong>Custom, non-skid pads</strong></p> <p> The step pads are textured for slip resistance and constructed from polypropylene for lasting protection against wear and tear.</p> <p> <strong>Fast, easy installation</strong></p> <p> Vehicle-specific brackets allow the side bars to contour to the vehicle and install easily with zero drilling or cutting required.</p>
```
After talking with @mcrandell  it turns out they only want to remove the "with zero drilling or cutting required" part.

**Comment by DavidVaini** [comment]
Max and Tim are going to get me a copy of all the original text and what they want it replaced with so make it still sound good.

**Comment by aaronrodgersmoustache** [comment]
Here you go, David. There was no reference in the Pro Series CategoryBriefs to "no-drill," so this is only 3" stainless and 3" semi-gloss black.

[Edit 3 IN Side Bar CategoryBrief.xlsx](https://github.com/aries-auto/ariesautomotive/files/82995/Edit.3.IN.Side.Bar.CategoryBrief.xlsx)

**Comment by mcrandell** [comment]
Spot Checked a handful of random side bars. didn't spot any text about drilling.
Thanks david.
