### ISSUE TITLE
Warranties Page Address

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#93]
Update the address on the Online Warranties page to use the Dallas warehouse location.

**Comment by ninnemana** [comment]
Can we change the customer service e-mail address to be the same as the CURT customer service email?

**Comment by DavidVaini** [comment]
changed the email address: 
https://github.com/aries-auto/ariesautomotive/commit/98232b1e0bc367b7735de4824067fbfd10d2cf5e
