### ISSUE TITLE
Search Results Tile

### ISSUE THREAD

**Issue by cowan14** [aries-auto/ariesautomotive#99]
![image](https://cloud.githubusercontent.com/assets/6673274/12360395/55204fd4-bb7d-11e5-9cfd-9abc32080568.png)

**Comment by baseigneurie** [comment]
This should be fixed now - https://github.com/aries-auto/ariesautomotive/commit/218f101f651774c31c590e3a4895edb9272c6ea1

**Comment by baseigneurie** [comment]
On second though, the problem may be effecting more results.

**Comment by baseigneurie** [comment]
Did some more adjustments and the tiles are looking better now.
https://github.com/aries-auto/ariesautomotive/commit/f6555dd193fbd580b439c28863ebd0d91afa16bd
https://github.com/aries-auto/ariesautomotive/commit/c4574221b40bb4148ead2817cd40d08a15a5f235
https://github.com/aries-auto/ariesautomotive/commit/440e3c5c9ae896fa9d9768e0ada4669dc334e2fb
